### ISSUE TITLE
errors regarding nested types lack context

### ISSUE THREAD

**Issue by avh4** [elm-lang/error-message-catalog#10]
In this example:
```elm
foo : List (List String) -> Int
foo _ = 0

bar = foo [""]
```

The following error is produced:
```
-- TYPE MISMATCH -------------------------------------------------------------- 

This argument is causing a type mismatch.

3| 
4|        foo [""]
5|            ^^^^

To be more specific, as I infer all the types, I am seeing a conflict between
this type:

    List String

and this type:

    String
```

This message is confusing because the underlined code `[""]` is of type `List String`, which makes the error seem to say that there is something of type `String` that doesn't match, but actually it is `List (List String)` that doesn't match.

A more helpful error would say that there is a conflict between types `List (List String)` and `List String`.  (Another alternative, although IMO less-helpful, would be to underline only `""` in the code snippet instead of `[""]`.

**Comment by evancz** [comment]
Here's the 0.16 version:

![screen shot 2015-10-28 at 1 53 16 am](https://cloud.githubusercontent.com/assets/1658058/10783674/b8a6feea-7d16-11e5-8461-634afc38ed4a.png)
