### ISSUE TITLE
Returning part of a type alias / forgetting a parameter

### ISSUE THREAD

**Issue by pinx** [elm-lang/error-message-catalog#104]
I have a two level data model, for which I was building a decoder. To start simple, I wanted to just decode the top level.

``` elm
type alias Category =
  { id : Int
  , name : String
  , products : List Product
  }

type alias Product =
  { id : Int
  , name : String
  }

categoryDecoder : Decoder Category
categoryDecoder = 
  Json.Decode.object2
    Category
    ("id" := Json.Decode.int)
    ("name" := Json.Decode.string)
```

The mistake I'm making here, is forgetting to set products to a default (empty list).
The message I get is:

```
The type annotation for `categoryDecoder` does not match its definition.

75│ categoryDecoder : Decoder Category
                      ^^^^^^^^^^^^^^^^
The type annotation is saying:

    Decoder { id : Int, name : String, products : List Product }

But I am inferring that the definition has this type:

    Decoder (List Product -> Category)
```

What would be helpful, is a message like:

```
The type annotation for `categoryDecoder` does not match its definition.

75│ categoryDecoder : Decoder Category
                      ^^^^^^^^^^^^^^^^
The type annotation is saying this function returns:

    Category

But I am inferring that the definition is returning a function that creates a Category:

    (List Product -> Category)

Did you forget an argument to the function that creates a Category?
```

**Comment by evancz** [comment]
With recent changes from #137, it will give a hint along the lines you want:

![screen shot 2016-08-09 at 9 09 54 pm](https://cloud.githubusercontent.com/assets/1658058/17541571/ae7e7de4-5e75-11e6-8b08-fa548d9fcd40.png)

Saying specific things about the function name that caused it is not really feasible in practice. In this particular case, it does not seem possible to get it down to exactly the kind of sentence you suggested.

Furthermore, we made a specific choice to display the entire type mismatch, not just the relevant subpart. Instead, we use "type diffing" so your eye is drawn to the relevant part of the type. This is really good, at it would hurt lots of other messages to change it. It has been improved to highlight missing arguments more clearly.

We could try to do more "realiasing" of types, but I think that should be in a separate issue.
