### ISSUE TITLE
Confusing message about "type applications should start with a type atom"

### ISSUE THREAD

**Issue by fredcy** [elm-lang/error-message-catalog#105]
I get the following error message from elm-make (0.16) when compiling the code following that.

```
-- TYPE MISMATCH ------------------------------------------------------ Main.elm

The type annotation for `update` does not match its definition.

17│ update : Users -> Action -> Users
             ^^^^^^^^^^^^^^^^^^^^^^^^
The type annotation is saying:

    Users -> Action -> Users

But I am inferring that the definition has this type:

    elm-make: type applications should start with a type atom
```

``` elm
module Main (..) where

type alias Users =
  { users : List User
  }

type alias User =
  { name : String
  }

type Action
  = X (Result () List)

update : Users -> Action -> Users
update model action model =
  case action of
    X result ->
      case result of
        Ok users ->
          Users (List.map2 (+) model.users users)
```

**Comment by fredcy** [comment]
That line with `List.map2` is wrong but the error message is little help in determining that.

I have not been able to reproduce the problem with any program smaller than the above.

**Comment by jvoigtlaender** [comment]
To me, that's not an issue of a confusing message. It's a proper compiler bug. See https://github.com/elm-lang/elm-compiler/issues/1326.

**Comment by fredcy** [comment]
This case does have an error message very similar to that compiler issue. Should I close this issue and just leave it linked from that one?

**Comment by jvoigtlaender** [comment]
I think that would make sense, yes.

Additionally, I just now realized that your code is not (only?) wrong in the `List.map2` line. The first line of the `update` definition is bad in its own way:

``` elm
update model action model =
```

Note the two parameters with same name. So this is also relevant: https://github.com/elm-lang/elm-compiler/issues/809.

**Comment by fredcy** [comment]
For the record, it wasn't my code. I was helping someone who posted their uncompilable code as a Gist. We got that working but the original version caused the error message above.
