### ISSUE TITLE
show types near the type error

### ISSUE THREAD

**Issue by avh4** [elm-lang/error-message-catalog#11]
In this example:
```elm
import Html

type Action = Change Float

init = { f = 2.5 }
update (Change f) c = { c | f <- f }
render c = toString c |> Html.text

mbox = Signal.mailbox 2.5
actions = Signal.map Change mbox.signal
model = Signal.foldp update init
main = model |> Signal.map render
```

In this case, the problem is that I forgot to pass `actions` as the last argument on line 11.

The following error is produced:
```
-- TYPE MISMATCH -------------------------------------------------------------- 

The right argument of (|>) is causing a type mismatch.

11| 
12|        model |> Signal.map render
13|                 ^^^^^^^^^^^^^^^^^

To be more specific, as I infer all the types, I am seeing a conflict between
this type:

    Signal.Signal Main.Action -> Signal.Signal { f : Float }

and this type:

    Signal.Signal a
```

The error could be improved by stating that `model` is the thing of type `Signal.Signal Main.Action -> Signal.Signal { f : Float }`

**Comment by evancz** [comment]
Here is the 0.16 error:

![screen shot 2015-10-28 at 1 52 12 am](https://cloud.githubusercontent.com/assets/1658058/10783648/8f48db54-7d16-11e5-99df-f02c2513f8bf.png)

I'll let you decide if this resolves the issue.

**Comment by evancz** [comment]
I think giving more comprehensive type information should not be in the console errors. I think this is better suited for type exploration within editors, and I expect keeping this issue open will not help us do that well.
