### ISSUE TITLE
Better to assume type annotation is always correct

### ISSUE THREAD

**Issue by jinjor** [elm-lang/error-message-catalog#110]
Sorry if you feel this is duplicated with others(e.g. #91 #70 ).

Here is a problematic case.

``` elm
import Html exposing (text)

main =
  text (toString buggy)

buggy : List Int -> List Float
buggy list =
  List.map (\i -> 1 / i) list
```

This code causes an error message.

```
-- TYPE MISMATCH ----------------------------------------------------- Main0.elm

The type annotation for `buggy` does not match its definition.

5│ buggy : List Int -> List Float
           ^^^^^^^^^^^^^^^^^^^^^^
The type annotation is saying:

    List Int -> List Float

But I am inferring that the definition has this type:

    List Float -> List Float

Hint: Elm does not automatically convert between Ints and Floats. Use `toFloat`
and `round` to do specific conversions.
<http://package.elm-lang.org/packages/elm-lang/core/latest/Basics#toFloat>

Detected errors in 1 module.
```

Now compiler is saying "the type annotation you declared is incorrect", but The real cause of the mismatch is `(\i -> 1 / i)`. I always write type annotation first and then implement the logic to fit the correct type, and believe this is a good practice for making API roles clear.

Is there any case this way goes wrong?

**Comment by ckoster22** [comment]
I could see this going both ways. It's not inconceivable that I write a type annotation one way only to realize during implementation that I'm better off returning a different type (for example) and forget to update the type annotation.

It probably comes down to what is the source of truth? The description of the function or the actual function implementation? I lean towards the latter but that's just my opinion.

**Comment by jinjor** [comment]
Thanks for your feedback.

I sometimes forget updating type annotations too, but I imagine even if the compiler assumes it was true, you can finally find what is wrong. I think the problem is which should be the stronger assumption, "It is Int because you say it is Int" or "It is Float because you use it like that". It is stressful for me that the compiler does not trust me.

**Comment by rtfeldman** [comment]
> Now compiler is saying "the type annotation you declared is incorrect"

To be fair, that's not quite what it's saying. 😄 

The precise message is:

```
The type annotation for `buggy` does not match its definition.
```

I can see how that would suggest that the annotation is the problem. Would you have found the message more helpful if it had said this instead?

```
The implementation of `buggy` does not match its type annotation.
```

Here's how the full error message would look with just that one line changed.

```
-- TYPE MISMATCH ----------------------------------------------------- Main0.elm

The implementation of `buggy` does not match its type annotation.

5│ buggy : List Int -> List Float
           ^^^^^^^^^^^^^^^^^^^^^^
The type annotation is saying:

    List Int -> List Float

But I am inferring that the definition has this type:

    List Float -> List Float

Hint: Elm does not automatically convert between Ints and Floats. Use `toFloat`
and `round` to do specific conversions.
<http://package.elm-lang.org/packages/elm-lang/core/latest/Basics#toFloat>

Detected errors in 1 module.
```

What do you think?

**Comment by jinjor** [comment]
The latter you suggested looks better to me. Thanks.

But there is another problem. I expected the following error message because I was sure `i` is an `Int` and the error was caused by the misunderstanding the usage of `(/)`.

```
-- TYPE MISMATCH ---------------------------------------------------------------

The right argument of (/) is causing a type mismatch.

10|     1 / i
            ^
(/) is expecting the right argument to be a:

    Float

But the right argument is:

    Int
```

Here is a comparison of the error message with Flow. Flow's one is what I expected here.

![type-inferrence-elm-vs-flow](https://cloud.githubusercontent.com/assets/2568148/16943476/e06b8234-4dd6-11e6-8976-d27af42cbdb6.png)

I'm not sure if this strategy of type inference is always better, and if another problem would not happen by switching the behavior.

**Comment by rtfeldman** [comment]
I can definitely see how pointing out the problematic call site alongside the type annotation can help illuminate where to look for the solution to the mismatch. That sounds really nice!

This seems like a case where two solutions are appropriate. One is a quick wording change, and the other is a bigger change.

**Comment by rtfeldman** [comment]
@jinjor the quick wording fix has been merged. Would you mind opening a separate issue in this repo for https://github.com/elm-lang/error-message-catalog/issues/110#issuecomment-233569457 ?

**Comment by jinjor** [comment]
@rtfeldman Thank you for your quick action! I created #140 .
