### ISSUE TITLE
type applications should start with a type atom

### ISSUE THREAD

**Issue by athanclark** [elm-lang/error-message-catalog#111]
I'm not exactly sure what this means, but it happened during type inference for this function:

``` elm
chunks : Int -> List a -> List (List a)
chunks n xs =
  let go : (List a, List (List a)) -> a -> (List a, List (List a))
      go (acc, ys) x =
        let size = List.length acc
        in  if size < n
            then (List.append acc (x::[]), ys)
            else ([]                     , List.append ys (acc::[]))
      (zs, zss) = List.foldl go ([],[]) xs
  in  List.append zss (zs :: [])
```

I've tried a number of tricks to adjust the terms, but for some reason it's not getting the system to work properly. Any ideas what I'm doing wrong here?

**Comment by jvoigtlaender** [comment]
The "inner type annotation" `go : (List a, List (List a)) -> a -> (List a, List (List a))` does not mean what you think it does. See https://github.com/elm-lang/elm-compiler/issues/1214.

**Comment by jvoigtlaender** [comment]
Your problem is that you assume `List.foldl` has type `(b -> a -> b) -> b -> List a -> b`, but it has type `(a -> b -> b) -> b -> List a -> b`.

**Comment by athanclark** [comment]
Ahh okay, but that should just cause a type mismatch, not throw a wrench in its spokes :\

Do you know what unification algorithm elm uses? It can't be just AlgorithmW is it? Is there a specific paper they modeled after, like bottom-up or outside-in?

**Comment by jvoigtlaender** [comment]
You are right that this should be reported as a type mismatch. That it instead crashes the compiler is a compiler bug. A compiler bug that has been reported repeatedly (and doesn't really need an additional issue here in this repository, I think). Look, for example, at: https://github.com/elm-lang/elm-compiler/issues/1326, https://github.com/elm-lang/elm-compiler/issues/1231, https://github.com/elm-lang/error-message-catalog/issues/105.

About your questions: No, I don't know. My impression from some cursory look into the type checking code a while ago was that unification was done in a quite ad-hoc way. But I may be wrong, and there may actually be a specific known algorithm followed there.

**Comment by rtfeldman** [comment]
Closing in favor of https://github.com/elm-lang/elm-compiler/issues/1231
