### ISSUE TITLE
Conflicting type variable bindings leads to contradictory error message

### ISSUE THREAD

**Issue by avh4** [elm-lang/error-message-catalog#113]
In 0.16: In the following, 

``` elm
type alias T a b c =
  { a : a, b : b, c : c }

f : T a b a -> ()
f _ = ()

x : T Int Float String -> ()
x = f
```

The error message is confusing and contradicts itself:

```
TYPE MISMATCH
The type annotation for `x` does not match its definition.

9| x : T Int Float String -> ()
The type annotation is saying:

    T Int Float Int -> ()

But I am inferring that the definition has this type:

    T Int Float Int -> ()
```

It shows the source code with the type annotation `T Int Float String -> ()`, and then states that the type annotation says `T Int Float Int -> ()`.

Instead, the error message should state "The type annotation is saying: `T Int Float String -> ()`"

**Comment by jvoigtlaender** [comment]
This "the compiler says two types are different, but shows the exact same two types" thing comes up so often. See https://github.com/elm-lang/elm-compiler/issues/1192 and all the issues showing up as references there. We _really_ need a process to avoid people opening duplicates after duplicates of issues. I think https://github.com/elm-lang/elm-compiler/pull/1342 is a good start.

**Comment by jvoigtlaender** [comment]
This is supposed to be fixed now. See https://github.com/elm-lang/elm-compiler/issues/1192#issuecomment-215254480.

**Comment by jvoigtlaender** [comment]
Actually it's not fixed. See https://github.com/elm-lang/elm-compiler/issues/1371.

**Comment by rtfeldman** [comment]
Closing this since there is a compiler issue tracking it.
