### ISSUE TITLE
You won't believe how he suggests improving the "I cannot find module 'Html'" message

### ISSUE THREAD

**Issue by ktec** [elm-lang/error-message-catalog#118]
Hello!!

As a total newbie, I installed Elm, wrote this as my first app:

```
import Html exposing (text)
main = text "Hello World"
```

And then when I ran `elm make` I was presented with this:

```
I cannot find module 'Html'.

Module 'Main' is trying to import it.

Potential problems could be:
  * Misspelled the module name
  * Need to add a source directory or new dependency to elm-package.json
```

Being a total newbie, I didn't know that this meant nor what to do about it. So I searched the web for explanations and eventually asked in the slack channel. I was (very helpfully) informed that I needed to run:

```
elm-package install --yes elm-lang/html
```

And that fixed everything \o/

It would be great if the error message suggested something similar to the information I received in the slack channel, so that if someone else gets to that problem, they can continue without having to ask really dumb questions 😄 

It wasn't clear that using `import Html` should equate to installing `elm-lang/html` package.

thanks for reading....

**Comment by rtfeldman** [comment]
@evancz given the number of upvotes, `Html` might be worth special-casing a hint. Seems like a lot of people run into it.

(In other non-special cases, might be worth adding to the hint something like "You may need to `elm-package install` a package from http://package.elm-lang.org to access this module.")

**Comment by evancz** [comment]
This is a pre-0.17.1 issue though. With 0.17.1, elm-package automatically includes elm-lang/html as a dependency on a new project, so this would not come up.

Given that, I don't know if there is anything more to do. Perhaps we will find other things like this that it makes sense to special case, but I don't know any right now. It may be possible to have a generic package suggester, but that's a much bigger thing.
