### ISSUE TITLE
Infix operators must be at the top level

### ISSUE THREAD

**Issue by szabba** [elm-lang/error-message-catalog#121]
When I try this on http://elm-lang.org/try :

``` elm
import Html

main =
    let
        (-) = ()
    in
        Html.text ""
```

I get a clear (for me) enough error that explains what's the problem

```
elm-make: can only define infix operators at the top level
elm-make: thread blocked indefinitely in an MVar operation
```

but
1. It doesn't look like the great messages Elm usually spoils us with.
2. It's followed by a message about MVars that's likely to confuse most people seeing it
3. Not everyone necessarily knows what "infix" means.

**Comment by evancz** [comment]
The rules about infix operators changed with 0.19 based on the reasoning [here](https://gist.github.com/evancz/769bba8abb9ddc3bf81d69fa80cc76b1). I believe the parser does not have a special case to detect when someone tries this, but it at least gives a normal error now:

```
-- PARSE ERROR -------------------------------------------------------- temp.elm

Something went wrong while parsing an expression (in parentheses) in main's
definition.

5|         (-) = ()
            ^
I was expecting:

  - a pattern, like `name` or (Just x)
  - a closing paren
```

Thanks for the report!
