### ISSUE TITLE
misleading type annotation error message

### ISSUE THREAD

**Issue by arnehormann** [elm-lang/error-message-catalog#125]
Copied and shortened from https://github.com/elm-lang/elm-compiler/issues/1410:

Taking `Bug.elm` with Elm 0.17

``` elm
import Html exposing (..)
import Html.App exposing (beginnerProgram)

main =
  beginnerProgram
    { model = {key = "", value = ""}
    , view = view
    , update = (\_ u -> u)
    }

type alias Model =
  { key: String
  , value: String
  }

view : Model -> Html msg
view m =
  div
    []
    [ strong [] [m.key]
    , text (": " ++ m.value)
    ]
```

I get this error on `elm-make Bug.elm --output=bug.html`:

```
-- TYPE MISMATCH ------------------------------------------------------- Bug.elm

The type annotation for `view` does not match its definition.

16| view : Model -> Html msg
           ^^^^^^^^^^^^^^^^^
The type annotation is saying:

    { ..., key : String } -> Html a

But I am inferring that the definition has this type:

    { ..., key : VirtualDom.Node a } -> Html a

Detected errors in 1 module.
```

The cause is `strong [] [m.key]`, it should be `strong [] [text [m.key]]`.

Though the compiler knows all intended types, it says the annotation in `view` is wrong and does not point to the wrong argument for `strong`.

**Comment by evancz** [comment]
Track this in #154, which should make this do what you expect.

**Comment by evancz** [comment]
Made some good progress on this. Here is the result with "assume the type annotation is correct" and an improvement to the type diffs that means we see `Html` instead of `VirtualDom.Node`:

![screen shot 2016-09-20 at 3 27 42 pm](https://cloud.githubusercontent.com/assets/1658058/18691128/d94a0d30-7f46-11e6-95c0-b48d4e07c26f.png)
