### ISSUE TITLE
Forgot to define the function

### ISSUE THREAD

**Issue by kittykatattack** [elm-lang/error-message-catalog#126]
Consider the following:

``` elm
update : Msg -> Model -> Model
  case message of 
    NoOp ->
      model
```

... Oops, I forgot to actually define the function!
It produces the following error message:

```
I ran into something unexpected when parsing your code!

28|   case message of
      ^
I am looking for one of the following things:

    end of input
    whitespace
```

Perhaps we can assist beginners with an error message like this:

```
It looks like you've written a type annotation for a function, but
forgot to actually define the function that uses it. You probably need 
to insert the following line of code at line number xxx :

update message model =

```

**Comment by evancz** [comment]
Thanks for reporting this! I'm working on a faster parser that also allows for improved error messages. Here's what it gives right now:

![screen shot 2016-12-15 at 9 57 46 pm](https://cloud.githubusercontent.com/assets/1658058/21251212/971c937e-c311-11e6-9c3d-fea7dca3d37b.png)

I think it's possible to do a little better, but it would be hard to get everything working right. I'm going to organize a meta issue to try to get a better feel for how that might work.
