### ISSUE TITLE
type mismatch highlights an unhelpful expression (List.foldl Array.append)

### ISSUE THREAD

**Issue by avh4** [elm-lang/error-message-catalog#13]
In the following example, the mistake is that `Array.push` should be used instead of `Array.append`:

```elm
import Graphics.Element exposing (show)
import Array

main = show <| List.foldl Array.append Array.empty [1,2,3]
```

The current error message is not helpful:

```
-- TYPE MISMATCH ---------------------------------------------------- Error2.elm

This argument is causing a type mismatch.

4|                List.foldl Array.append Array.empty [1,2,3]
                                                      ^^^^^^^
To be more specific, type inference is leading to a conflict between this type:

    Array.Array a

and this type:

    number
```

A more helpful message would show that `[1,2,3]` **and** `Array.append` together are causing the mismatch.  It would also be helpful to see the full type `List (Array.Array a)` and `List number` (see #10).  It would also be helpful to see the full type of `Array.append` as resolved in this context (a mismatch between `number -> Array.Array a -> Array.Array a` and `Array.Array a -> Array.Array a -> Array.Array a`.

**Comment by evancz** [comment]
Here is the 0.16 message:

![screen shot 2015-10-28 at 1 48 19 am](https://cloud.githubusercontent.com/assets/1658058/10783590/1b8d0578-7d16-11e5-81b2-c9cbf7348df5.png)

It does not address all of your concerns though, so can you open a new issue showing the new error and a mock of what you would prefer the error to be?
