### ISSUE TITLE
Bad fields in Html.program record give confusing messages

### ISSUE THREAD

**Issue by ghost** [elm-lang/error-message-catalog#131]
error is `subscriptions = Sub.none`
solution is `subscriptions model = Sub.none`
![fixed by subscriptions model couldn t error message just say subscriptions is missing its argument](https://cloud.githubusercontent.com/assets/8081877/16340275/20f85442-3a1f-11e6-914a-035a795196f2.png)

It's as though Elm is starting at the top (with `main`), rather than at the bottom and seeing that `subscriptions` is just missing an argument.

**Comment by ghost** [comment]
Another example where the error message is much more complicated, but the problem the same.

```
-- TYPE MISMATCH ----------------------------------------------------- share.elm

The argument to function `program` is causing a mismatch.

16|     App.program
17|>        { init = init
18|>        , view = view
19|>        , update = update
20|>        , subscriptions = subscriptions
21|>        }

Function `program` is expecting the argument to be:

    { ...
    , update :
          Main.Msg -> (Int -> Main.Model) -> ( Int -> Main.Model, Cmd Main.Msg )
    , view : (Int -> Main.Model) -> Html Main.Msg
    }

But it is:

    { ...
    , update :
          Main.Msg
          -> { accountNumber : String
          , donation : Float
          , donees : List IndexedDonee
          , minimumSend : Float
          , name : String
          , percentage : Float
          , sortCode : String
          , uid : Int
          }
          -> ( { accountNumber : String
          , donation : Float
          , donees : List IndexedDonee
          , minimumSend : Float
          , name : String
          , percentage : Float
          , sortCode : String
          , uid : Int
          }
          , Cmd a
          )
    , view :
          { d
              | donees :
                    List
                        { c
                            | id : Int
                            , model :
                                  { b
                                      | accountNumber : String
                                      , details : Bool
                                      , donations : number
                                      , minimumSend : number
                                      , name : String
                                      , sortCode : String
                                  }
                        }
          }
          -> Html Main.Msg
    }

Hint: Does your program have flags? Maybe you want `programWithFlags` instead.

Detected errors in 1 module.                                        
```

![screen shot 2016-06-26 at 19 59 59](https://cloud.githubusercontent.com/assets/8081877/16364629/ea4ead8a-3be3-11e6-9231-b84860bd2906.png)
![screen shot 2016-06-26 at 21 22 28](https://cloud.githubusercontent.com/assets/8081877/16364636/2f397f38-3be4-11e6-83d9-8f87e8147710.png)
There was an argument missing.
![screen shot 2016-06-26 at 20 00 09](https://cloud.githubusercontent.com/assets/8081877/16364633/048e4e3a-3be4-11e6-93d4-fa999e6edc28.png)

**Comment by evancz** [comment]
I think it makes sense to centralize anything like this in #137

**Comment by evancz** [comment]
Nevermind, this is a different thing.

**Comment by evancz** [comment]
I made it so unification will try to pin down more fields, thereby making the error more specific. Here's the version I have now:

![screen shot 2016-08-08 at 5 43 02 pm](https://cloud.githubusercontent.com/assets/1658058/17501088/4375d69a-5d90-11e6-826d-ead0dd07539e.png)

I think it's possible to "stack" hints, so if there are additional hints, they'd appear together. In this case, I think it could be something like "It looks like a problem with the `subscriptions` field. It looks like a function needs 1 more argument." Not sure how that interacts with all possible hints, but it seems doable.

Would stacking make this better?

**Comment by rtfeldman** [comment]
Yes, for sure! Stacking sounds _great_ here.

Also, this looks super awesome! 😻

**Comment by evancz** [comment]
The question is if it looks great in all the other possible situations ;)

I'll try to do something with stacking hints then. Should be fairly simple, as long as the hints combine to form reasonable sentences.

**Comment by ghost** [comment]
To be fair to type annotations, I raised this issue before I learned that type annotations tend to help narrow things down in this situation. But more helpful hints would also help too.

**Comment by evancz** [comment]
Alright, here's a version with stacked hints:

![screen shot 2016-08-09 at 12 38 14 pm](https://cloud.githubusercontent.com/assets/1658058/17530850/313b58d0-5e2e-11e6-9a9b-ebc77fe98084.png)

---

Here are some other examples of nested and stacked hints.

### Nested Mismatch

``` elm
point1 = { x = 3 // 1, y = 4 }
point2 = { x = "bird", y = 4 }

foo = { point = point1 } == { point = point2 }
```

![screen shot 2016-08-09 at 12 44 11 pm](https://cloud.githubusercontent.com/assets/1658058/17531009/ec98191a-5e2e-11e6-9f0c-0e19ce7c8e15.png)

### Nested Mismatch with Hint

``` elm
point1 = { x = 3 // 1, y = 4 }
point2 = { x = 3.0, y = 4 }

foo = { point = point1 } == { point = point2 }
```

![screen shot 2016-08-09 at 12 41 00 pm](https://cloud.githubusercontent.com/assets/1658058/17530927/81f37546-5e2e-11e6-80bc-5b9e8d807f98.png)

**Comment by rtfeldman** [comment]
This is so awesome!!! 😻 

This definitely would have helped me through some mismatches related to large Models. (I assume it still shows the diff like this, even if the problematic fields are each nested 3+ levels deep?)

For the binary operations hint, would it be feasible to include the operator as context? e.g. "With binary operations like `==` I always figure out the left side first." (I think beginners may not realize what "binary operation" refers to by itself.)

Also seems like https://github.com/elm-lang/error-message-catalog/issues/63 is related to this work, although maybe not.

**Comment by evancz** [comment]
I'd open a new issue about saying `==` explicitly in that hint. I think that's a good idea, but I think it makes sense to try it in a world without backtick infix, which make it trickier.

The missing field thing is unrelated technically, though it is related in that it has to do with records.
