### ISSUE TITLE
Suggest names that are not imported at all

### ISSUE THREAD

**Issue by ghost** [elm-lang/error-message-catalog#132]
**Edited by @evancz**

If someone wants `String.reverse` but has not imported `String`, they will get an error message like this:

![suggest string reverse given its argument model is a string](https://cloud.githubusercontent.com/assets/8081877/16340606/002d86b8-3a21-11e6-9677-630ac3f80c0d.png)

It would be nice if name suggestions could come from _all_ packages.

**Comment by evancz** [comment]
I think your #128 is a clearer version of the same thing, so let's consolidate it into that one.
