### ISSUE TITLE
Forgot beginnerProgram/program in main

### ISSUE THREAD

**Issue by ghost** [elm-lang/error-message-catalog#133]
The text in the input doesn't show in the div below as expected. Could be told Html.App not being used in main, given presence of Html and update function.
![text in input doesn t show in div below because no update argument in main could be told update function not being used in main](https://cloud.githubusercontent.com/assets/8081877/16340688/64ef2d5e-3a21-11e6-8e7b-0a1412278d83.png)

**Comment by rtfeldman** [comment]
Thanks for the suggestion! This will probably be surfaced as a warning ("unused function") once Dead Code Elimination gets merged into a future release of the compiler, so I'm going to close this until then.
