### ISSUE TITLE
Uses wrong `toString`

### ISSUE THREAD

**Issue by ghost** [elm-lang/error-message-catalog#135]
I'm using [elm-integer](http://package.elm-lang.org/packages/javcasas/elm-integer/2.0.2). In my code, `toString integer` does `Basics.toString integer` rather than `Data.Integer.toString integer` (which is what I want), even though `integer` is a `Data.Integer`. Normally you get the error about "more than one possible `toString`, which one do you want?" but I guess because `Basics.toString` takes any type, it just uses that. Suggest uses function closest to its type.

**Comment by rtfeldman** [comment]
Thanks for reporting this! Unfortunately, `toString integer` is valid code, and reporting an error for valid code would be bad times. 😄

**Comment by ghost** [comment]
How about just a warning asking for `toString` to be qualified with a namespace?

**Comment by ghost** [comment]
I guess my question is: why does `toString integer` do `Basics.toString integer`, rather than `Data.Integer.toString integer`? It seems that type `a` takes precedence over a more specific type (in this case, `Integer`)? Should it?

**Comment by rtfeldman** [comment]
Introducing warnings is a case where different people might want different behaviors. Some think the warning helps, others think it's complaining about code that shouldn't be changed.

I'd ask what different people on https://groups.google.com/forum/#!forum/elm-discuss think!

**Comment by ghost** [comment]
Really sorry, I was doing `import Data.Integer` without `exposing`! No wonder the compiler wasn't erring: there weren't more than one `toString`.

**Comment by ghost** [comment]
I do feel though that there is a usability issue here. With a choice between `import` and `import exposing`, I think I've shown that when writing code you have to remember which one you've done! I'm not sure whether or where to raise this exactly. I'm now thinking, what's the point of `import` if the code is shorter with `import exposing` and the compiler's got our back when there's a naming conflict?
