### ISSUE TITLE
Passing too few arguments 

### ISSUE THREAD

**Issue by rtfeldman** [elm-lang/error-message-catalog#137]
[SSCCE](http://sscce.org/) in elm-repl:

```
> import String
> "foo" ++ String.join "blah"
-- TYPE MISMATCH --------------------------------------------- repl-temp-000.elm
​
The right argument of (++) is causing a type mismatch.
​
4│   "foo" ++ String.join "blah"
              ^^^^^^^^^^^^^^^^^^
(++) is expecting the right argument to be a:
​
    String
​
But the right argument is:
​
    List String -> String
​
Hint: I always figure out the type of the left argument first and if it is
acceptable on its own, I assume it is "correct" in subsequent checks. So the
problem may actually be in how the left and right arguments interact.
```

It would be nice if this said:

```
Hint: Did you forget to pass an argument to String.join?
```

In general, any error of the form "expected `a` but got `b -> a`" seems like it could helpfully suggest "maybe you forgot an argument."

Similarly, it seems plausible that "expected `a` but got `c -> b > a`" could suggest two missing arguments.

**Comment by rtfeldman** [comment]
Longer example: https://github.com/elm-lang/error-message-catalog/issues/131

**Comment by evancz** [comment]
Here's what I have for the initial example:

![screen shot 2016-08-08 at 3 17 47 pm](https://cloud.githubusercontent.com/assets/1658058/17498292/5c3ae48c-5d7b-11e6-94b5-13556b2498a6.png)

There are two improvements:
1. You get a hint telling you about how many arguments may be missing.
2. The type diff highlights the missing args, then diffs the "aligned" arguments.

In this case, it means we highlight exactly the thing that is missing, but I'm not sure it'll be nice in all scenarios.

**Comment by rtfeldman** [comment]
Here is the longer example transcribed:

``` elm
import Html.App exposing (program)
import Html exposing (..)
import Html.Events exposing (..)

main =
    program
        { init = init
        , update = update
        , view = view
        , subscriptions = subscriptions
        }

init =
    ( i, Cmd.none )

type Msg = Roll

update msg model =
    case msg of
        Roll ->
            ( 2, Cmd.none )

subscriptions = Sub.none

view model =
    div []
        [ button [ onClick Roll ] [ text "Roll " ]
        , div [] [ text (toString model) ]
        ]
```

How does the error look for this one?

**Comment by evancz** [comment]
It tells you about the missing argument, but the actual problem there is in how record field mismatches are figured out. It may be possible to do more "assume fields are correct as you see them" to make things more specific, but that should be addressed separately from the missing args stuff.

![screen shot 2016-08-08 at 4 16 29 pm](https://cloud.githubusercontent.com/assets/1658058/17499688/dce1f65e-5d83-11e6-9a83-33a556491f28.png)

**Comment by evancz** [comment]
@rtfeldman , see https://github.com/elm-lang/error-message-catalog/issues/131#issuecomment-238422857 for more on record problems. In theory, that should make error messages better for all large records with polymorphic fields, but more testing is needed. Could mess things up too. Not sure!
