### ISSUE TITLE
Trying to define function members in records

### ISSUE THREAD

**Issue by ianmackenzie** [elm-lang/error-message-catalog#138]
In the REPL:

``` elm
q = { foo = \x -> x + 1 }
```

is fine but

``` elm
r = { foo x = x + 1 }
```

gives

```
-- SYNTAX PROBLEM -------------------------------------------- repl-temp-000.elm

I ran into something unexpected when parsing your code!

3|   r = { foo x = x + 1 }
       ^
I am looking for one of the following things:

    end of input
    whitespace
```

The ideal error message would presumably be a caret pointing at the first `x` saying `expected '='` or something like that (unless this syntax becomes valid in a future version of Elm, which would be nifty!)

**Comment by evancz** [comment]
I'm improving the parser, and was able to make this one a lot nicer:

![screen shot 2016-12-15 at 2 56 05 am](https://cloud.githubusercontent.com/assets/1658058/21217510/28451cd6-c272-11e6-8d38-6aa856ba7ee7.png)

Thanks for the report!

**Comment by ianmackenzie** [comment]
Looks great, thanks!
