### ISSUE TITLE
Assume type annotation is always correct

### ISSUE THREAD

**Issue by jinjor** [elm-lang/error-message-catalog#140]
(This issue has been moved from #110 to clarify the problem)

Here is a problematic case.

``` elm
import Html exposing (text)

main =
  text (toString transform)

transform : List Int -> List Float
transform list =
  List.map (\i -> 1 / i) list
```

This code produces an error message.

```
-- TYPE MISMATCH ----------------------------------------------------- Main0.elm

The implementation of `transform` does not match its type annotation.

5│ transform : List Int -> List Float
           ^^^^^^^^^^^^^^^^^^^^^^
The type annotation is saying:

    List Int -> List Float

But I am inferring that the definition has this type:

    List Float -> List Float

Hint: Elm does not automatically convert between Ints and Floats. Use `toFloat`
and `round` to do specific conversions.
<http://package.elm-lang.org/packages/elm-lang/core/latest/Basics#toFloat>

Detected errors in 1 module.
```

The real cause of the mismatch is `(\i -> 1 / i)`. Now compiler is assuming `(\i -> 1 / i)` is `Float -> Float` and then `list` is `List Float`, but I'm sure `list` is `List Int` and `i` is an `Int`. I think this is a bit confusing and feel strange that "inference is stronger than annotation". I expect compiler to "assume type annotation is always correct".

In this case, I expect some message like following.

```
-- TYPE MISMATCH ---------------------------------------------------------------

The right argument of (/) is causing a type mismatch.

7|     1 / i
            ^
(/) is expecting the right argument to be a:

    Float

But the right argument is:

    Int
```

Here is a comparison between Elm and Flow (sorry, example is another one). Flow's message is closer to my expectation.
![type-inferrence-elm-vs-flow](https://cloud.githubusercontent.com/assets/2568148/16976348/20345ae6-4e89-11e6-90da-8dcd3b44e4cc.png)

**Comment by evancz** [comment]
Follow along in #154

**Comment by evancz** [comment]
Worked on this on the flight home from elm-conf and ended up with this:

![screen shot 2016-09-20 at 3 31 47 pm](https://cloud.githubusercontent.com/assets/1658058/18691239/6d9e26ce-7f47-11e6-8419-98ddd9c59947.png)

Thanks for the report!

**Comment by jinjor** [comment]
Looks nicer!
So not figuring out `i : Int` is another problem? Or not a problem? I understand the second hint but would like to know this is a temporary workaround or a permanent solution.
Anyway, "Assume type annotation is correct" looks solved. Thanks!
