### ISSUE TITLE
Missing : leads to error on first ->

### ISSUE THREAD

**Issue by aklaing** [elm-lang/error-message-catalog#142]
I know this is ridiculously basic but ... I wrote some code similar to the following:

```
modifyAList Int -> List A -> List A
modifyAList i alist = <... deleted ...>
```

Clearly it is missing a colon before the type of the function.  I got the following error message:

```

I ran into something unexpected when parsing your code!

632| modifyAList Int -> List A -> List A
                     ^
I am looking for one of the following things:

    an equals sign '='
    whitespace

Detected errors in 1 module.
```

Just a note that we should modify the error message to include a colon as one of the things that may be missing, in keeping with the huge reputation Elm has for fantastic error messages.

**Comment by ianmjones** [comment]
Here's an SSCCE:

```elm
module Main exposing (..)

import Html exposing (Html, text)


type alias Model =
    String


view Model -> Html msg
view model =
    text model


main : Html a
main =
    view "wibble"
```

**Comment by evancz** [comment]
Same as #62, but let's keep both open for now.

**Comment by evancz** [comment]
Here's the message from the new parser:

![screen shot 2016-12-15 at 9 31 04 pm](https://cloud.githubusercontent.com/assets/1658058/21250824/d04cbb82-c30d-11e6-8991-4dbeb822ba05.png)

Do you think that covers this case alright?

It is hard to do significantly better because the following code is actually valid:

```elm
modifyAList Int = 32
```

It's clearer why if you do a few renames:

```elm
type Unit = Unit

f1 Unit = 1

f2 Nothing = 2
```

Point is, an upper case item can be an argument. The compiler would *eventually* reject `Nothing` as an argument because you do not also handle `Just`, but that happens much later in the pipeline. It would also *eventually* reject `Int` as an argument because there's no such type constructor, but again, that happens after parsing.

**Comment by ianmjones** [comment]
If you're new to the language the new parser's message would probably still not help much as it doesn't mention anything about the annotation likely being ill-formated or that a ":" might be missing from it. It reads as though there might be something wrong with the function definition.

Also, what happened to my comment with the SSCCE?

**Comment by aklaing** [comment]
So I understand the error message better now, but I agree with
@ianmjones that overall, the problem is still not resolved.  If it
were easy to fix, the reason to push the issue would be that a new
user (especially) may have a higher probability of making the former
mistake (with type annotation) than the latter (value definition).  I
trust your judgement however that it may not be worth fixing, given
the amount of code changes that may be required to make it work.

Just to clarify my (rough) understanding of the issue:

```
2| modifyAList Int -> List A -> List A
               ^1  ^2
```

I'm guessing that what is happening here is that there are two
possibilities, a type annotation rule, and a "value definition" rule.
The type annotation grammar rule is missing a colon and fails early at
`^1`.  The value definition rule fails later, at `^2`.  So that is the one
that gets reported to the user.

To fix this, it might be required to keep track of more than one
possible parse tree (ie when more than one grammar rule may apply).
One would then have to flag all the possibilities that have failed
when the last one of them fails.

It does sound like something that may require major changes.

**Comment by evancz** [comment]
I am finishing up an overhaul of the parser that focused a lot on producing better error messages. In the original case, my development build is now producing:

```
-- MISSING COLON? ----------------------------------------------------- temp.elm

I was not expecting to see an arrow here:

1| modifyAList Int -> List A -> List A
                   ^^
This usually means a : is missing a bit earlier in a type annotation. It could
be something else though, so here is a valid definition for reference:

add : Int -> Int -> Int
add x y =
  x + y

Try to use that format with your `modifyAList` definition!
```

I think that is as good as I can get it for this particular scenario.

**Comment by ianmjones** [comment]
That's excellent @evancz, way clearer, especially with the simple example. Nice one!

**Comment by aklaing** [comment]
That works great! Thanks for the hard work.
