### ISSUE TITLE
Use `as` name rather than module name in NAMING ERROR message

### ISSUE THREAD

**Issue by ghost** [elm-lang/error-message-catalog#143]
```
This usage of variable `toString` is ambiguous.

316|                 g (v `mul` (fromInt 10)) (denominator x) n (toString u ++ ".")
                                                                 ^^^^^^^^
Maybe you want one of the following?

    Basics.toString
    Data.Integer.toString

```

I've imported Data.Integer as `I` in this file so I would like it to say `I.toString` so I just write that in, otherwise I see this message and go off to write `Data.Integer.toString` and that's wrong

**Comment by evancz** [comment]
Not sure what to fix without an http://sscce.org/, so it makes sense to close this one. If you can reproduce it, open a new issue with the relevant code snippet.

@rtfeldman, feel free to do this kind of thing!
