### ISSUE TITLE
Confusing message when trying to access a field that does not exist in model

### ISSUE THREAD

**Issue by gabriela-sartori** [elm-lang/error-message-catalog#148]
When I was teaching Elm to a friend, he accidentally tried to access a field "countt" that don't exist.
But he was not able to understand the error message!
Something like "Field `countt` seems to not exist in model" would be better!

```
import Html            exposing (..)
import Html.Attributes exposing (..)
import Html.Events     exposing (onClick)
import Html.App        exposing (beginnerProgram)

type Msg = Inc | Dec
type alias Model = { count : Int }

view : Model -> Html Msg
view model =
    div [] [ button [ onClick Inc ] [ text "+" ]
           , br [] []
           , text <| toString model.count
           , br [] []
           , button [ onClick Dec ] [ text "-" ]
           ]

update : Msg -> Model -> Model
update msg model =
    case msg of
        Inc ->
            { model | count = model.count + 1 }
        Dec ->
            { model | count = model.countt - 1 }

main : Program Never
main =
    beginnerProgram { model = Model 0, view = view, update = update }
```

![image](https://cloud.githubusercontent.com/assets/6143964/17307469/b5baca56-580b-11e6-977c-50462d40d7ba.png)

**Comment by evancz** [comment]
Thanks for the report! Follow along in #154. That will make it so this would trigger the normal record mismatch errors.

**Comment by evancz** [comment]
I got it down to a smaller http://sscce.org/

``` elm
type Msg = Increment | Decrement

type alias Model = { count : Int }

update : Msg -> Model -> Model
update msg model =
  case msg of
    Increment ->
      { model | count = model.count + 1 }

    Decrement ->
      { model | count = model.countt - 1 }
```

Here is the new error message:

![screen shot 2016-09-20 at 4 58 28 pm](https://cloud.githubusercontent.com/assets/1658058/18693048/9b43b2b8-7f53-11e6-8fa1-b0c10aabb34f.png)

This is the result of assuming the type annotation is correct and the changes in https://github.com/elm-lang/elm-compiler/commit/b17a4f051af5780950b790eb50ecb4093c699ab0 specific to trying to access fields that do not exist.
