### ISSUE TITLE
Misleading "Based on its definition"

### ISSUE THREAD

**Issue by ghost** [elm-lang/error-message-catalog#149]
I'm setting up for SVG: 

![problem](https://cloud.githubusercontent.com/assets/8081877/17326529/d7fcb310-58a9-11e6-9c71-843d9e827a06.png)

I've accidentally missed `.width` off `windowSize` in the `width` expression. I get this:

![error](https://cloud.githubusercontent.com/assets/8081877/17326555/0a1be8e8-58aa-11e6-93b3-28c70dbb89f4.png)

"Based on its definition" makes me go off looking at my model's definition, which is fine:

![screen shot 2016-08-02 at 12 11 01](https://cloud.githubusercontent.com/assets/8081877/17326598/3db30812-58aa-11e6-9bb2-975394234b81.png)

Spotted the missing `.width` by chance and program compiles. Suggest pointing towards it in the error message.

**Comment by evancz** [comment]
I think the root confusion here is that `model` and `Model` are not the same thing. Not sure how to address that in a nice way.

Given that we also do not have an http://sscce.org for this, I think it makes sense to close for now.

If you can create an SSCCE, please open a new issue with a suggestion of how to do a better job given the root problem. (Also, please paste in the code, not as an image. Transcribing code out of images sucks.)
