### ISSUE TITLE
Tab characters disallowed

### ISSUE THREAD

**Issue by rtfeldman** [elm-lang/error-message-catalog#15]
The following contains **no tab characters** and compiles successfully:

```elm
module Main where

one = if True then 1
              else 0
```

If you replace any of the spaces before `else` with a tab character (`\t`), you get:

```
## ERRORS in Main.elm ##########################################################

-- SYNTAX PROBLEM ----------------------------------------------------- Main.elm

I ran into something unexpected when parsing your code!

4| 	            else 0
   ^
I am looking for one of the following things:

    an 'else' branch
    whitespace
```

This was originally reported in https://github.com/elm-lang/elm-platform/issues/16.

This message could be improved by simply saying something like "You have a tab character here instead of a space. Tab characters are never allowed in Elm files, so please convert this file to use only spaces."

**Comment by jessitron** [comment]
+1 This bit me today.
Tab characters ARE whitespace, so the message is confusing.

**Comment by rtfeldman** [comment]
Idea for an efficient solution: have the lexer accept tab characters, but then as soon as we encounter one, throw a syntax error.

**Comment by evancz** [comment]
@rtfeldman, take a swing at a PR

**Comment by rtfeldman** [comment]
Challenge accepted! Although I probably won't have bandwidth for the next ~2 weeks.

**Comment by tikotzky** [comment]
This just bit me today as well...
as @jessitron said above this really threw me because the `^` in the error message is point at what seemingly looks like whitespace...

```
7│    message
   ^
I am looking for one of the following things:

    whitespace
```

**Comment by evancz** [comment]
Error I am seeing in 0.17.1

```
-- SYNTAX PROBLEM ---------------------------------------------------- crash.elm

A tab character was found, but all whitespace (including indentation) must be
spaces not tabs.

3|              then 1
   ^
I am looking for spaces, not tabs.
```
