### ISSUE TITLE
Include operator name with "binary operations" hint

### ISSUE THREAD

**Issue by rtfeldman** [elm-lang/error-message-catalog#155]
(Splitting this out from https://github.com/elm-lang/error-message-catalog/issues/131#issuecomment-238742578 as its own issue.)

```
point1 = { x = 3 // 1, y = 4 }
point2 = { x = 3.0, y = 4 }

foo = { point = point1 } == { point = point2 }
```

The hint currently says:

```
With binary operations, I always figure out the left side first.
```

I remember being confused by this the first few times I encountered it; I think beginners may not realize what "binary operations" refers to by itself.

Suggestion to make it clear what "binary operations" refers to:

```
With binary operations like `==` I always figure out the left side first.
```

**Comment by evancz** [comment]
It will look like this in the next 0.18 alpha:

![screen shot 2016-10-26 at 5 02 05 pm](https://cloud.githubusercontent.com/assets/1658058/19749455/f6d12f0a-9b9d-11e6-9e9c-49845ba373dc.png)
