### ISSUE TITLE
Trying to update a record with =

### ISSUE THREAD

**Issue by rtfeldman** [elm-lang/error-message-catalog#16]
Here's a mistake I've made before: accidentally using `=` in a record update when I meant `<-`

```elm
record1 : { foo : String, bar : String }
record1 = { foo = "bar", bar = "baz" }

record2 : { foo : String, bar : String }
record2 = { record1 | foo = "baz" } -- whoops!
```

This yields the following type mismatch:

```
The type annotation for 'record2' does not match its definition.

record2 : { foo : String, bar : String }

To be more specific, type inference is leading to a conflict between this type:

    { bar : String, foo : String }

and this type:

    { bar : String, foo : String, foo : String }
```

With the current error message, it took me a bit to figure out what I'd done. ("Why is it making two `foo` fields? How is that even possible? What's going on here?")

It seems like whenever you get this type error, and the desired record type contains duplicate fields (in this case two entries for `foo : String`), this would be a great time for a helpful suggestion like so:

```
Did you mean to use `foo <-` instead of `foo =` in your record update?
```

**Comment by mgold** [comment]
I encountered this lately. +1 for fixing it or choosing syntax to make it irrelevant.

**Comment by evancz** [comment]
0.16
