### ISSUE TITLE
Specify line number of declaration in missing whitespace scenario

### ISSUE THREAD

**Issue by brunogirin** [elm-lang/error-message-catalog#164]
In this scenario, it would be very useful to specify the line number at which what looks like a new declaration was found. This is probably due to an unbalanced parens as in issue #9 and indicating the line number where the problem was found would help a lot.

```
-- SYNTAX PROBLEM -------------------------- ./src/Imby/Taxonomy/LocalSearch.elm

I need whitespace, but got stuck on what looks like a new declaration. You are
either missing some stuff in the declaration above or just need to add some
spaces here:


I am looking for one of the following things:

    whitespace
```

**Comment by dbulic** [comment]
Similar:

```
-- SYNTAX PROBLEM ----------------------------------------- ././Admin/Events.elm

I ran into something unexpected when parsing your code!


I am looking for one of the following things:

    "\""
    "\\"
    "\n"
    "\r"

Detected errors in 1 module. 
```

**Comment by domenkozar** [comment]
Same here:

```
-- SYNTAX PROBLEM ----------------------------------------------- ./src/View.elm

I need whitespace, but got stuck on what looks like a new declaration. You are
either missing some stuff in the declaration above or just need to add some
spaces here:


I am looking for one of the following things:

    whitespace

Detected errors in 1 module.  
```

**Comment by brunogirin** [comment]
I just had it with Elm 0.18 due to a missing closing bracket at the end of a test declaration.

**Comment by evancz** [comment]
I can't do anything about this without an http://sscce.org. I have no idea how any of these messages were produced!

That said, I believe these kinds of things will be improved with the new parser I'm working on. If you want to provide an SSCCE, make a separate self-contained issue with that information.
