### ISSUE TITLE
Missing "lambda" character

### ISSUE THREAD

**Issue by j-panasiuk** [elm-lang/error-message-catalog#169]
I forgot to put **\** sign at the beginning of anonymous function

``` elm
import Html exposing (text)

double = a -> 2 * a

main = text (toString (double 5))
```

This results in

```
-- SYNTAX PROBLEM --------------------------------------------------------------

I ran into something unexpected when parsing your code!

4| double = a -> 2 * a
              ^
I am looking for one of the following things:

    end of input
    whitespace
```

This is exactly how I would use ES6 arrow function (except using fat arrow), so it tripped me up a couple of times

**Comment by evancz** [comment]
Here's the new error message:

![screen shot 2016-12-15 at 9 25 41 pm](https://cloud.githubusercontent.com/assets/1658058/21250746/20d4930a-c30d-11e6-9e5a-0e382f7765d5.png)

Would that have helped you?

**Comment by j-panasiuk** [comment]
It's much better than the infamous "end of input / whitespace" charade ;)
Thanks!
