### ISSUE TITLE
Trying to use single quotes for strings

### ISSUE THREAD

**Issue by rtfeldman** [elm-lang/error-message-catalog#17]
Since in JavaScript single quotes work the same way as double quotes, a JS programmer might reflexively try to write the following:

```elm
str = 'foo'
```

Currently this yields the following fairly unhelpful syntax error:

```
I ran into something unexpected when parsing your code!

1| str = 'foo'
I am looking for one of the following things:

    a closing '''
```

It would be better if it explained that in Elm, `'` is used for single characters only, and `"` is required for multi-character Strings.

**Comment by evancz** [comment]
Thanks for the report. Should be fixed in the next big release!

![screen shot 2016-08-06 at 9 33 07 pm](https://cloud.githubusercontent.com/assets/1658058/17460479/5e1a056c-5c1d-11e6-9be1-ff6ca1cfbfc5.png)

**Comment by evancz** [comment]
I think something went wrong such that this error message didn't trigger when those parser changes were all done. With the recent batch of improvements, this message also got much more specific:

![screen shot 2016-12-15 at 10 25 19 pm](https://cloud.githubusercontent.com/assets/1658058/21251682/680944de-c315-11e6-872e-5c201be60fa3.png)

**Comment by ellogwen** [comment]
sadly double quotes are hard to type for some keyboard layouts. I got used to single quotes because of this and now I am in pain writing elm :)

**Comment by congwenma** [comment]
would it be too much to ask if we can have elm determine if the input is a char or string and the programmer would just use `'` singlequote, and user can make single chars string explicitly by double quote.

**Comment by tiagojdf** [comment]
This error message is not displayed when you are defining a record. Took me a while to figure out that:
```
bill = { name = 'Gates', age = 57 }
```
Was invalid, because I got the following error message:
```
-- SYNTAX PROBLEM -------------------------------------------- repl-temp-000.elm

The = operator is reserved for defining variables. Maybe you want == instead? Or
maybe you are defining a variable, but there is whitespace before it?

4|   bill = { name = 'Gates', age = 57 }
          ^
Maybe <http://elm-lang.org/docs/syntax> can help you figure it out.
```
