### ISSUE TITLE
Unhelpful error when missing a type constructor in an if branch

### ISSUE THREAD

**Issue by martinmodrak** [elm-lang/error-message-catalog#171]
Compiling this snippet using elm-make

```
type LostCause = Activity | Nerves

type GameState = Running | Lost LostCause 

modifyState : GameState -> GameState
modifyState state =
                         --The error is below: "Lost" is missing an argument (should be "Lost Activity")
          if not (state == Lost) then Running
          else state
```

Gives this error:

```
-- TYPE MISMATCH ------------------------------------------------ 

The branches of this `if` produce different types of values.

8|>          if not (state == Lost) then Running
9|>          else state

The `then` branch has type:

    GameState

But the `else` branch is:

    LostCause -> GameState

Hint: These need to match so that no matter which branch we take, we always get
back the same type of value.
```

Which is confusing - 
a) the type of the `else` branch is obviously GameState 
b) the problem is not in the values of the if statement but actually in the condition `not (state == Lost)` which misses an argument and should read `not (state == Lost Activity)` - took me a while to figure this one out (I had a much larger if statement)...

**Comment by evancz** [comment]
Here's what I am seeing with the latest version of the 0.18 alpha on my machine:

![screen shot 2016-10-26 at 5 25 09 pm](https://cloud.githubusercontent.com/assets/1658058/19749841/3a18b1fe-9ba1-11e6-8f1d-4acf3dbc6e23.png)

So this should be nicer in the next release. Thanks for the report!
