### ISSUE TITLE
Type Checker Failure - Unable to generalize a type variable. It is not unranked.

### ISSUE THREAD

**Issue by gilbertkennen** [elm-lang/error-message-catalog#185]
I wasn't sure if this was best for the compiler issues or here. I figured that since it seems to only fail when it should fail that this was the better place to drop it.

The code is obviously incorrect. The interaction seems to be between the `a` in `foo` and the `List Float` in `bar`. If `List` is removed or `Float` or `Bool` is changed to a type variable or the `x` parameter omitted, then everything starts working again. I used different definite types to illustrate that they don't seem to matter, but it still fails in the same way even if they are more correct.

```Elm
foo : a -> Int
foo x =
    bar x


bar : List Float -> Bool
bar x =
    "baz"
```

```
elm-make: It looks like something went wrong with the type inference algorithm.
Unable to generalize a type variable. It is not unranked.
Please create a minimal example that triggers this problem and report it to
<https://github.com/elm-lang/elm-compiler/issues>
CallStack (from HasCallStack): error, called at src/Type/Solve.hs:255:3 in elm-compiler-0.18-6b7ElUUnEdQ18JS9q9eLxH:Type.Solve elm-make: thread blocked indefinitely in an MVar operation
```

**Comment by simonh1000** [comment]
I got the same error with this code when the type definition of b was not commented out

```
valMulti : (a -> Validation e c) -> List a -> Validation e (List c)
valMulti valFunc bs =
    let
        -- go : b -> Validation e (List c) -> Validation e (List c)
        go b acc =
            succeed (::)
                |> andMap (valFunc b)
                |> andMap acc
    in
        L.foldr go (succeed []) bs
```

**Comment by evancz** [comment]
I'm gonna track this in https://github.com/elm-lang/elm-compiler/issues/1613 because it is a bug!

Thanks for the very simple SSCCE @gilbertkennen!

**Comment by evancz** [comment]
Based on commit https://github.com/elm-lang/elm-compiler/commit/4b25980d93ada12236c794f35570e197be82f787, I am now seeing the following error in my development build!

![screen shot 2018-03-06 at 2 01 46 pm](https://user-images.githubusercontent.com/1658058/37061033-fbf2417e-2146-11e8-8711-3629dca0411f.png)

> **Note:** You may see extra qualifiers on types in this error. That is part of the dev build, but should not appear in the final thing.

Thanks again for the report!
