### ISSUE TITLE
Mismatch parenthesis

### ISSUE THREAD

**Issue by bcse** [elm-lang/error-message-catalog#19]
```elm
import Html exposing (text)

(

main =
  text "Hello, World!"
```

The current error message doesn't mark the parenthesis at line 3.

```
-- SYNTAX PROBLEM ----------------------------------------------------
I ran into something unexpected when parsing your code!

5| main =

I am looking for one of the following things:

    whitespace
```

**Comment by evancz** [comment]
Thanks for the report! Going to continue tracking in meta issue #177.

**Comment by evancz** [comment]
Working on new parser that gives better error messages. Here's the new error:

![screen shot 2016-12-15 at 4 37 31 pm](https://cloud.githubusercontent.com/assets/1658058/21244796/d7a0a732-c2e4-11e6-9d65-9ca014830757.png)

The trick is that you *can* start a definition with `(` like `(x,y) = 42`. If you have specific requests of how to improve this message further, open a new issue.
