### ISSUE TITLE
Hint that exponentiation is ^ when wrongly using undefined **

### ISSUE THREAD

**Issue by drathier** [elm-lang/error-message-catalog#193]
When trying to use `**` for exponentiation (`10**24`, as used in Python) the error message says that the variable `**` is not defined. In this case, it would be helpful if the compiler asked `Did you mean exponentiation? (10^24)`

If you did define `**` yourself, this hint wouldn't show, since it's no longer an undefined variable error.

**Comment by evancz** [comment]
Made some changes a moment ago. The error should be like this in the next release:

```elm
-- UNKNOWN OPERATOR -------------------------------------------------------- temp.elm

I do not recognize this (**) operator:

3|   10 ** 24
        ^^
Switch to (^) for exponentiation. Or switch to (*) for multiplication.
```

Thanks for mentioning this! Easy to improve, and will definitely help some newcomers out!
