### ISSUE TITLE
undefined variables gives issue about single quotes

### ISSUE THREAD

**Issue by alok** [elm-lang/error-message-catalog#200]
I open `elm-repl` and run the following code:

```elm
-- not defined
s
```

and get the error message:

```
Ran into a single quote in a variable name. This was removed in 0.18!

9|   , section, nav, article, aside, header, footer, address, main', body
                                                                  ^
Change it to a number or an underscore, like main_ or main1

Or better yet, choose a more descriptive name!
```

It should first tell me that the variable is undefined.

**Comment by evancz** [comment]
I think this is due to having an old `elm-stuff/` lying around. I'd need more info to replicate, but I don't think this should happen now that folks have cleared that out by now.

Sorry for the trouble, and thank you for reporting this issue!
