### ISSUE TITLE
Whitespace before type declaration

### ISSUE THREAD

**Issue by jessitron** [elm-lang/error-message-catalog#21]
When I put a space accidentally before [this line](
https://github.com/jessitron/elm-architecture-tutorial/blob/e7492a314d7f04fb63f30428b4329f192df7b92a/4/InteractionCounter.elm#L16):

`update : (innerAction -> aModel -> aModel) -> innerAction -> Model aModel -> Model aModel`

then I get the compile error:

    Detected errors in 1 module.
    ## ERRORS in InteractionCounter.elm ############################################
    -- SYNTAX PROBLEM --------------------------------------- InteractionCounter.elm
    I ran into something unexpected when parsing your code!
    16|  update : (innerAction -> aModel -> aModel) -> innerAction -> Model aModel -> Model aModel
                ^
    I am looking for one of the following things:
        end of input
        whitespace

... which confused me.

**Comment by rtfeldman** [comment]
Thanks and welcome, @jessitron! :D

**Comment by garthgoldwater** [comment]
I'm not sure if this should be an separate issue, but accidentally indenting `main` also gives you the same confusing error message:

```
-- SYNTAX PROBLEM ----------------------------------------------- SignupForm.elm

I ran into something unexpected when parsing your code!

20│   main =
           ^
I am looking for one of the following things:

    end of input
    whitespace

Detected errors in 1 module.
```

**Comment by evancz** [comment]
I improved it a bit. For the following program:

``` elm

x = 4

 str : String
str =
  "foo"
```

You get this error:

```
-- SYNTAX PROBLEM ---------------------------------------------------- crash.elm

A singe colon is for type annotations. Maybe you want :: instead? Or maybe you
are defining a type annotation, but there is whitespace before it?

4|  str : String
        ^
Maybe <http://elm-lang.org/docs/syntax> can help you figure it out.
```

**Comment by rtfeldman** [comment]
> A _singe_ colon

@evancz typo?
