### ISSUE TITLE
Tell user explicitly that they're trying to use a type as a constructor

### ISSUE THREAD

**Issue by drathier** [elm-lang/error-message-catalog#222]
If you have a `type T = T A` and you try to construct `T` using `T`, having imported the type but not the constructor, you get asked if you ment to use the constructor `T` instead, but there's no mention that you're trying to use a type as a constructor. Since they're sharing the same name, it took a while to figure out what happened.

**Comment by evancz** [comment]
I need an http://sscce.org/ to verify that I have fixed things like this.

I kinda get what you mean, but I'd need a new issue to check.
