### ISSUE TITLE
Check for import errors before cyclic imports

### ISSUE THREAD

**Issue by drathier** [elm-lang/error-message-catalog#227]
If A imports a nonexisting function from B, and B imports whatever from A, you get an error about a cyclic dependency. Since the only thing A imports from B is nowhere to be found, it's a false alarm, and the real problem is that A is importing something that is exported from B, but not defined in B.

**Comment by evancz** [comment]
This is more of a feature suggestion I think.

Even if the thing you want from `B` does not exist, you still cannot have cyclic dependencies.

I think the idea is that you could resolve the cycle more easily if you had more information. If so, I'd say open a different issue with an SSCCE proving that this case exists in practice. This seems like it'd be quite hard to implement on first glance, so better examples make it more compelling to look into.
