### ISSUE TITLE
Confusing message when using single quotes for strings  inside lists

### ISSUE THREAD

**Issue by ellogwen** [elm-lang/error-message-catalog#229]
Trying out elm with the elm-repl but instantly got confused be the below error message

![image](https://user-images.githubusercontent.com/22261975/28982057-a2a04f5c-7954-11e7-9ca8-a007cc26ec5a.png)

Since double quotes are hard to write for me on my keyboard layout I got used to using single quotes for defining string. Hadn't thought that that would be a big deal in elm. Well, the error message is misleading anyway .

**Comment by kipanshi** [comment]
Having the same issue, the string can't be defined with single quotes, but the message is misleading.

**Comment by evancz** [comment]
Thank you for the report! In 0.19 the error message looks like this:

```
> names = ['Alice', 'Bob', 'Charlie']
-- PARSE ERROR ------------------------------------------------------------- elm

Ran into a bad use of single quotes.

3| names = ['Alice', 'Bob', 'Charlie']
            ^^^^^^^
If you want to create a string, switch to double quotes:

    'this' => "this"

Hint: Unlike JavaScript, Elm distinguishes between strings like "hello" and
individual characters like 'A' and '3'. If you really do want a character
though, something went wrong and I did not find the closing single quote.
```
