### ISSUE TITLE
Long records in error messages difficult to manually diff

### ISSUE THREAD

**Issue by rtfeldman** [elm-lang/error-message-catalog#23]
Consider this code:

```elm
type alias Person =
  {
    firstName : String,
    lastName : String,
    
    hairColor : String,
    eyeColor : String,

    address : String,
    phoenNumber : String,
    email : String,
    
    pets : Int
  }

getFullName : Person -> String
getFullName person =
  person.firstName ++ " " ++ person.lastName
  
fullName =
  getFullName
    {
      firstName = "Sam",
      lastName = "Sample",
      
      hairColor = "Brown",
      eyeColor = "Brown",
      
      address = "1337 Elite st",
      phoneNumber = "867-5309",
      email = "foo@bar.com",
      
      pets = 2
    }
```

If you try to compile it, you get this type mismatch:

```
The 1st argument to function `getFullName` has an unexpected type.

21|   getFullName
22|>    {
23|>      firstName = "Sam",
24|>      lastName = "Sample",
25|>      
26|>      hairColor = "Brown",
27|>      eyeColor = "Brown",
28|>      
29|>      address = "1337 Elite st",
30|>      phoneNumber = "867-5309",
31|>      email = "foo@bar.com",
32|>      
33|>      pets = 2
34|>    }

As I infer the type of values flowing through your program, I see a conflict
between these two types:

    Person

    { address : String
    , email : String
    , eyeColor : String
    , firstName : String
    , hairColor : String
    , lastName : String
    , pets : Int
    , phoneNumber : String
    }
```

The underlying problem is a small typo: the definition of `Person` has the field listed as `phoenNumber` rather than `phoneNumber`. However, that is very difficult to deduce from this error message!

It would be really great if, when there's a type mismatch between two records, the compiler could diff the two records' fields and tell you what's different about them. In that case, this one could have been:

```
As I infer the type of values flowing through your program, I see a conflict
between these two types:

    Person

    { address : String
    , email : String
    , eyeColor : String
    , firstName : String
    , hairColor : String
    , lastName : String
    , pets : Int
    , phoneNumber : String
    }

Comparing the former to the latter...

  The following fields were missing:

    phoenNumber : String

  The following fields were added:

    phoneNumber : String
```

Instead of spending awhile hunting down the difference, this would have instantly directed me to the source of the problem.

This one would be a major time-saver for me, as I frequently work with records that have 10+ fields, and these errors don't seem to get significantly faster to debug with experience.

**Comment by flip111** [comment]
This would be a good improvement :+1:

**Comment by evancz** [comment]
Resolved in 0.16:

![screen shot 2015-10-28 at 1 42 22 am](https://cloud.githubusercontent.com/assets/1658058/10783456/36020b2a-7d15-11e5-9453-5ac4b56951ac.png)

**Comment by flip111** [comment]
huge improvement :+1:

**Comment by rtfeldman** [comment]
![jayz](https://cloud.githubusercontent.com/assets/1094080/10796907/70a05532-7d5d-11e5-9521-98eccc25ebc7.gif)

**Comment by flip111** [comment]
Does this also fix https://github.com/elm-lang/error-message-catalog/issues/23#issuecomment-145948396 ? or should i open up a new issue for this?

**Comment by evancz** [comment]
How could I know? There is no code there that'd let me reproduce it and test.

The error messages are far better for type annotation as well though, so I suspect it's nicer. I'd recommend trying out 0.16 alpha3 (available on elm-dev) to see if the code you have in mind is nicer. If not, it makes sense to open an issue with a http://sscce.org/

**Comment by evancz** [comment]
Also, I hope I don't sound too harsh there! I just need some additional stuff, and there's no real way to know "how to be great at github issues" unless you do it wrong a lot. That's how I learned, and I'd say I still have a lot to learn!

**Comment by flip111** [comment]
all good all good. I just figured if you knew by any chance you could say it. But you don't know so we can try with 0.16 and give more feedback on that when it's stable. It's not a problem. thanks for this improvement already i think many people will be happy to get easier messages about records
