### ISSUE TITLE
Svg Inferred for Html

### ISSUE THREAD

**Issue by AppShipIt** [elm-lang/error-message-catalog#26]
I was demoing Elm to a student and got confused by an error. Minimal code:
```elm
import Html exposing (p, text)
main = p
  text "Hello, World!"
```
Expected error:
```
As I infer the type of values flowing through your program, I see a conflict
between these two types:
    List Html.Html
    String
```
Actual error:
```
As I infer the type of values flowing through your program, I see a conflict
between these two types:
    List Svg.Svg
    String
```
Explicitly annotating `main` fixes one error but not another. I suspect there's an implicit import bungling inference.

**Comment by evancz** [comment]
Hmm, I guess we don't have a good tiebreaker when a value can be re-aliased in two ways or something. Thanks for the report, this is an important one!

**Comment by TheSeamau5** [comment]
Could the tie-breaker be based on which library is imported? For example, in this case, clearly Svg is nowhere to be seen in the code.

**Comment by evancz** [comment]
It's tricky and gets into deep details of type inference. Not sure what the fix is, or exactly why it's happening this way. I don't *think* there's a super simple solution, but I always think that when the type inferencer is involved :P

**Comment by dnalot** [comment]
Much lower hanging fruit: I always forget which is the expected type and which was found in the message.

**Comment by agrafix** [comment]
I agree with @dnalot , it should be made more clear what was the expected and what was the actual type, like haskell.
