### ISSUE TITLE
Union types haven't been renamed to Custom types in error messages 

### ISSUE THREAD

**Issue by rl-king** [elm-lang/error-message-catalog#271]
A quick grep gives the following files in which there are error messages that refer to `union types`.
```
compiler/src/Reporting/Error/Type.hs
compiler/src/Reporting/Error/Cononicalize.hs
compiler/src/Reporting/Error/Syntax.hs
compiler/src/Optimize/Port.hs
```

I could PR this but as they're still called `Union Types` internally, I'll submit this first, since there might be an idea/plan for this.

**Comment by evancz** [comment]
These have been getting updated as I have been going through error messages for 0.19.1, so running `grep "union type" compiler/src/Reporting -r` produces no results these days.

There is one still in `compiler/src/Optimize/Port.hs` but that is there in case certain compiler bugs are introduced, not for reporting things to users. I'll tweak it in a second anyway!

I think the name will probably remain the same in a lot of the compiler code. It may get renamed slowly over time, but I don't think it's worth the risk of doing so many renames all at once.
