### ISSUE TITLE
Package install with malformed package name produced unhelpful error message

### ISSUE THREAD

**Issue by MartinSStewart** [elm-lang/error-message-catalog#282]
I ran `elm install elm-geometry` in PowerShell using Window 10 and got the following error message:
```
elm.exe: TODO show possible arg configurations
CallStack (from HasCallStack):
  error, called at ui/terminal/src\Terminal\Args\Error.hs:281:13 in main:Terminal.Args.Error
```
After a couple minutes I realized that I should have written `elm install ianmackenzie/elm-geometry` instead but I think it would be more helpful if the error message returned was something along the lines of `Failed to install package.  I expected the package name formatted as author/package-name`.

**Comment by evancz** [comment]
Thanks for reporting this! On my development build, I am seeing the following error message:

```
$ elm install elm-geometry
I am having trouble with this argument:

    elm-geometry

It is supposed to be a <package> value, like one of these:

    elm/browser
    elm/core
    elm/parser
    elm/regex

```

So it looks like it got fixed as part of the infrastructure improvements there. The fixed version should become available once Elm 0.19.1 is released. Thank you for reporting this case!

**Comment by evancz** [comment]
I think it can be improved a bit more though. I'll give it a shot and get back to you!

**Comment by evancz** [comment]
Ah, it's a bit tricky. I know if I really start working on it there is a high chance the project will grow a bit larger than makes sense, so I think it makes sense to wait on it for now.
