### ISSUE TITLE
"UNEXPECTED EFFECT MODULE" error message points to a 404

### ISSUE THREAD

**Issue by danabrams** [elm-lang/error-message-catalog#289]
The error message given by the compiler when trying to create an effect module points to a URL that returns a 404.

The link provided is "https://elm-lang.org/0.19.0/effect-modules".

**Comment by evancz** [comment]
In the development build, it is giving the following error message:

```
-- BAD MODULE DECLARATION --------------------------------------------- temp.elm

I cannot parse this module declaration:

1| effect module SSCCE exposing (sscce)
                       ^
This type of module is reserved for the @elm organization. It is used to define
certain effects, avoiding building them into the compiler.
```

I initially thought there was more to say about it, but when I actually sat down to write it up, I felt like this was everything I wanted to say about it.

So this should be resolved in Elm 0.19.1 and above.
