### ISSUE TITLE
Forgetting commas in lists, it doesn't suggest a comma

### ISSUE THREAD

**Issue by jessitron** [elm-lang/error-message-catalog#29]
I often forget to put commas in lists. Because Clojure doesn't require commas, and neither do function parameters.
And then it gives me a type error, and ... I don't know whether it's possible, but it would be lovely if it suggested that maybe I need a comma.

Code [here](https://github.com/jessitron/elm-sydron/blob/5fb58f9e80a3b701d3326465305a61fa02790b64/src/Sydron.elm#L46)

Error:

```
-- TYPE MISMATCH ------------------------------------------------ src/Sydron.elm

Function `input` is expecting 2 arguments, but was given 8.

46|        Html.input [ Attr.placeholder "owner", Attr.id "repo-owner"] []
47|>       Html.input [ Attr.placeholder "repository", Attr.id "repo-name"] []
48|>       Html.button [ Attr.style [("background", "url(img/elm-button.jpg")]] []

As I infer the type of values flowing through your program, I see a conflict
between these two types:

    a -> b

    Html
```

**Comment by rtfeldman** [comment]
I hereby solemnly do swear I didn't put @jessitron up to this. :wink:

**Comment by evancz** [comment]
Here's the latest version of the error message:

![screen shot 2015-10-28 at 3 33 02 pm](https://cloud.githubusercontent.com/assets/1658058/10805207/3f1953e8-7d89-11e5-9d73-653d415b5752.png)

It now mentions the possibility of missing commas. Do you think there's more to be done? If not, can you close this issue?

**Comment by evancz** [comment]
Hmm, now that I start talking about code guessing, maybe it is not totally insane. This case is actually a pretty nice example of a time when you could probably guess things pretty well. You know you are in a list, you know how many args are expected so you could just try a comma and see what happens. I think this would be a very big project that would only make sense when we are supporting IDEs better, but it may make sense to open something new suggesting that we try this.
