### ISSUE TITLE
Did you forget to add [] around it?

### ISSUE THREAD

**Issue by mordrax** [elm-lang/error-message-catalog#292]
![image](https://user-images.githubusercontent.com/4709169/54794442-967e1d00-4c9b-11e9-9597-2dacc8cb0e0c.png)

The hint is ambiguous at best and misleading at worst suggesting that the highlighted `Field Date` needs to be a list.
It so happens that line 28, the `view` function is the one that needs to return a list.

**Comment by mordrax** [comment]
```
type alias Field a =
    { raw : String
    , value : a
    , view : a -> List (Html (Msg a))
    , label : String
    , validation : a -> List String
    }
```

**Comment by evancz** [comment]
Ended up removing the hint in https://github.com/elm/compiler/commit/0cd361d54c3a56940ebf94882069adf1fbc4600e. Seems like it's actively confusing in some cases, and in general, probably very rarely the real problem.

Thank you for reporting this!
