### ISSUE TITLE
"a record" vs "this record"

### ISSUE THREAD

**Issue by rtfeldman** [elm-lang/error-message-catalog#32]
Now that compiler error messages provide such clear context, it feels weird that the "field missing" error doesn't acknowledge that you already know which record is the broken one.

```
The 1st argument to function `isOver50` has an unexpected type.

9|          isOver50 hermann
                     ^^^^^^^
Looks like a record is missing the field `age`
```

It seems like this would be nicer, assuming it wouldn't cause confusion in certain cases:

```
The 1st argument to function `isOver50` has an unexpected type.

9|          isOver50 hermann
                     ^^^^^^^
Looks like this record is missing the field `age`
```

See further discussion at https://github.com/elm-lang/elm-compiler/pull/974

**Comment by evancz** [comment]
Not relevant anymore with 0.16.

In the future, please include the code that triggers the error message as well.
