### ISSUE TITLE
Confusing comparable type error with number

### ISSUE THREAD

**Issue by robertjlooby** [elm-lang/error-message-catalog#33]
The error message for a `comparable` with `number` is very confusing. 

program: 

```
f = 1 < "hello"
```

output: 

```
The right argument of (<) is causing a type mismatch.

1| f = 1 < "hello"
As I infer the type of values flowing through your program, I see a conflict
between these two types:

    comparable

    String

```

Which is confusing because `String` _is_ a `comparable`. If the `number` is instead an `Int` or `Float` you get a much clearer error message.

**Comment by evancz** [comment]
Thanks for the report! Can you edit the original post to show a small Elm program that can be pasted into elm-lang.org/try along with a copy of what `elm-make` spits out so we can assess this without reconstructing those things?

**Comment by jvoigtlaender** [comment]
Isn't that [this bug](https://github.com/elm-lang/elm-compiler/issues/1013) in the type checker? That is, it's not an issue of a bad error message, but rather the type checker does something wrong. Once that is fixed, there won't be any (good or bad) error message anymore.

**Comment by jvoigtlaender** [comment]
Oh, well, no, actually. `1 < "hello"` will still be an error, of course. But fixing the type checker bug in https://github.com/elm-lang/elm-compiler/issues/1013 will hopefully turn the error message here into something complaining about `Int` vs. `String` rather than about `comparable` vs. `String`.

**Comment by evancz** [comment]
Here's the error that's produced by 0.16 which should be out somewhat soon:

![screen shot 2015-10-28 at 1 37 53 am](https://cloud.githubusercontent.com/assets/1658058/10783387/9d7332ee-7d14-11e5-8bec-741eebf45b27.png)

Thanks for the report!
