### ISSUE TITLE
Saying "type" instead of "type alias" could use a better clue

### ISSUE THREAD

**Issue by jessitron** [elm-lang/error-message-catalog#35]
This morning, I declared a useless type when I meant type alias.  Details, including code and the compiler output, in [this gist](https://gist.github.com/jessitron/4adfdd364238a83e31d4).

Does it even make sense to say:

```elm
type Action = SomeOtherComponent.Action
```

I don't think so. I wish it would say, "Yo, that doesn't make sense. Did you mean 'type alias' ? " instead of "conflicting types ..." later on.

Consulted with Richard, he said this surprises him, so I don't feel bad for being hugely frustrated and stymied by it.

**Comment by evancz** [comment]
This is really surprising to me as well. I'm sort of surprised this even passes the parser. Thanks for reporting this!

**Comment by markhamburg** [comment]
In explaining Elm to others (and to myself for that matter) having both types and type aliases in the language is confusing. I can imagine being loathe to change the syntax at this point, but it would be easier to explain to people if one instead used `type Foo =` for what are now type aliases and something like `type Foo = union A | B | C` for what are currently types. There may well be other downsides besides the costs of a syntax change but I would take this error message report as actually a report about an error that it's too easy to make when using the language.

**Comment by evancz** [comment]
Okay, this does not pass the new parser. Instead you get this error message:

![screen shot 2016-12-15 at 9 14 23 pm](https://cloud.githubusercontent.com/assets/1658058/21250526/8b628e5e-c30b-11e6-8cfa-9bb0a8c92f72.png)

It now says you are in a union type, but I guess more could be done to distinguish further. It may make sense to add links that explain the syntax, but that can be done separately.
