### ISSUE TITLE
Accidental infix operator declaration

### ISSUE THREAD

**Issue by rtfeldman** [elm-lang/error-message-catalog#39]
If you attempt to put an infix character (e.g. `$`) in the middle of a variable name, you get a surprising error:

<img width="1247" alt="screen shot 2015-09-04 at 8 41 59 am" src="https://cloud.githubusercontent.com/assets/1094080/9687914/ef586cb8-52e0-11e5-9bd0-9dc12cb8a4e0.png">

It would be clearer if instead defining infix operators in this style required putting spaces on either side of the operator (and really, that might be a good rule for invoking infix operators as well) so that this can be reported as an illegal variable name.

**Comment by evancz** [comment]
This way of defining infixes does not exist in 0.16
