### ISSUE TITLE
Obscure error for bad indentation on multi-line function

### ISSUE THREAD

**Issue by dbrwn** [elm-lang/error-message-catalog#40]
Perhaps related to #14.
New to the language.  I could not find anything super definitive on the indentation sensitivity for function declarations.  There are a few references to indentation sensitivity for specific areas of syntax, such as on the Elm Syntax page for Conditionals and Let Expressions. 

<pre>
Elm REPL 0.4.2 (Elm Platform 0.15.1)
  See usage examples at <https://github.com/elm-lang/elm-repl>
  Type :help for help, :exit to exit
</pre>

With indentation:

<pre>
> goodName name = \
|   name == "David"
<function> : String -> Bool
</pre>

Without indentation:

<pre>
> perfectName name = \
| name == "Dave"
## ERRORS in repl-temp-000.elm #################################################

-- SYNTAX PROBLEM -------------------------------------------- repl-temp-000.elm

I ran into something unexpected when parsing your code!

3|   perfectName name = 
                      ^
I am looking for one of the following things:

    end of input
    whitespace

> 
</pre>

**Comment by rtfeldman** [comment]
@dbrwn Thanks for the feedback! If I understand the problem correctly, it's that this does not compile:

```elm
perfectName name =
name == "Dave"
```

...whereas this does:

```elm
perfectName name =
    name == "Dave"
```

...and the error message for the former doesn't make it clear that indentation is the source of the problem. Does that sound right?

**Comment by dbrwn** [comment]
@rtfeldman Yep that's the issue.  There may be a separate issue for the documentation to clarify that the indentation is required, but I may have missed where it says that.  I suppose the absence of any braces should have tipped me off that everything (almost everything?) would be indentation sensitive.

**Comment by rtfeldman** [comment]
Actually very few things are indentation sensitive; I believe the complete list is:

1. Function declarations
2. `let` binding clauses
3. `case` expression clauses

**Comment by TonyCronin** [comment]
@dbrwn @rtfeldman  Getting the same issue on elm-repl on Ubuntu 14.04 installed from npm 3.3.6. When following along using the **elm-repl** with the core language examples at documentation at https://guide.elm-lang.org/core_language.html. I generate a whitespace error when I fail to give the body of a function one or more spaces. This is not explicitly stated in the documentation:

>  Using a backslash in the REPL lets us split things on to multiple lines. We use this in the definition of over9000 above. Furthermore, it is best practice to always bring the body of a function down a line. It makes things a lot more uniform and easy to read, so you want to do this with all the functions and values you define in normal code.

If the documentation was changed too: 

> "...It is best practice to always bring the body of the function down a line. **If you are using the elm-repl make sure you indent your function body by 1 space otherwise this will generate a parsing error.**"

I believe it would stop newbs from encountering this 'gotcha'. I note that the on line editor: http://elm-lang.org/try gives a sensible error message for the same whitespace issue (see below). I think the issue could be cleared up by a) changing the error message on the elm-repl to match the behavior of the on line documentation or b) explicitly stating manual indentation is required in the function body:

Error message for white space on http://elm-lang.org/try:

`-- SYNTAX PROBLEM --------------------------------------------------------------`
`I need whitespace, but got stuck on what looks like a new declaration. You are either missing some` 
`stuff in the declaration above or just need to add some spaces here:`
`3| n * n
`   ^ I am looking for one of the following things:     whitespace`

**Comment by benforeva** [comment]
I agree with @TonyCronin. I'm new to Elm and I got stuck with this as well defining the `over9000` function from the [Core Language section](https://guide.elm-lang.org/core_language.html) of the guide.

``` bash
> over9000 powerLevel = \
| if powerLevel > 9000 then "It's over 9000!!!" else "meh"
-- SYNTAX PROBLEM -------------------------------------------- repl-temp-000.elm

I ran into something unexpected when parsing your code!

3|   over9000 powerLevel =
                                         ^
I am looking for one of the following things:

    end of input
    whitespace
```

I found the solution in [an issue from 2015](https://github.com/elm-lang/elm-repl/issues/67).

Reflecting on my experience I think the compiler message didn't help me because of the following reasons:
1. The  caret points to the first line when the error is in the second line.
2. The line that follows the `\` appears to already have whitespace. The line starts with - `|` instead of `|`.

**Comment by rogeriochaves** [comment]
I ran an elm workshop today and had this problem, one of the participants was having trouble with indentation, and she couldn't figure out how to fix it by the error message, she was typing something like this:

``` elm
model =
{ name = "Foo" }
```

IMO having an example in the error message would be very helpful already

ps. this was the only issue, everybody else also got errors from the compiler but they all could fix them very quickly without my help, I was thrilled ;D

**Comment by evancz** [comment]
Was able to improve cases like this. Here's the new output for @rtfeldman's SSCCE:

![screen shot 2016-12-15 at 3 11 10 am](https://cloud.githubusercontent.com/assets/1658058/21217927/478f36c4-c274-11e6-80a0-395cb190f2ac.png)

I think it's possible to include more context in the code snippet, but the comments are quite specific now.
