### ISSUE TITLE
Compact error messages

### ISSUE THREAD

**Issue by Apanatshka** [elm-lang/error-message-catalog#41]
This proposal is to have *an option* for more terse messages, specifically for people familiar with the elm-compiler error messages who want **much** smaller messages. I'm not lobbying to for changes in the current error messages!

Consider the following code snippet and corresponding error message in Elm 0.15.1.

```elm
import Html

view { username, password, errors } =
  let
    string = "" ++ errors.username ++ errors.password
  in Html.div [] []

main = view { username = "", password = "" }
```

```
## ERRORS in compact-errors.elm ################################################

-- TYPE MISMATCH -------------------------------------------- compact-errors.elm

The 1st argument to function `view` has an unexpected type.

8|        view { username = "", password = "" }
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Looks like a record is missing the field `errors`

As I infer the types of values flowing through your program, I see a conflict
between these two types:

    { b |
        errors : { a | password : String, username : String },
        password : String,
        username : String
        }

    { password : String, username : String }


Detected errors in 1 module.       
```

I would prefer a shorter error message, as I'm already used to the kinds of error messages that I get from the compiler. I prefer these shorter messages so I can see the whole error message in a small terminal window, and can quickly scroll and glance over the errors. 
For example, something like this:

```
## ERRORS in compact-errors.elm ################################################

-- TYPE MISMATCH -------------------------------------------- compact-errors.elm

Record is missing field `errors`
8|        view { username = "", password = "" }
    { b |
        errors : { a | password : String, username : String },
        password : String,
        username : String
        }
/=  { password : String, username : String }


Detected errors in 1 module.       
```

(You can use colouring of the code to remove the need for `^^^^^`, remove blank lines, only mention the hint. Perhaps there is more that can be done, but I don't want to degrade the information too much. )

[Original issue on elm-compiler](https://github.com/elm-lang/elm-compiler/issues/936)

**Comment by rtfeldman** [comment]
I appreciate the spacing and the `^^^^` but I'd appreciate if things were more concise.

Based on how I use compiler output, I'd make 3 changes to the status quo:

1. "Bottom-line it for me" by putting the most helpful message first, namely `Looks like a record is missing the field 'errors'`
2. Cut the `### ERRORS #####` line - all I ever look at are the `-- TYPE MISMATCH -----` lines anyway
3. Cut `Detected errors in 1 module.` - this has never been useful to me; seems like more of a candidate for a hypothetical `elm-make -v` or something.

This is what I'd prefer:

```
-- ERROR: TYPE MISMATCH -------------------------------------------- compact-errors.elm

Looks like a record is missing the field `errors`

8|        view { username = "", password = "" }
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

The 1st argument to function `view` has an unexpected type. I see a conflict
between these two types:

    { b |
        errors : { a | password : String, username : String },
        password : String,
        username : String
        }

    { password : String, username : String }
```

**Comment by Apanatshka** [comment]
@rtfeldman Looks like I messed up my post. I'll edit the original post, but I'll explain here too:
My proposal is to have *an option* for more terse messages, specifically for people familiar with the elm-compiler error messages who want **much** smaller messages. I'm not lobbying to for changes in the current error messages.
If you want to discuss improvements to the current messages adapted, please open a separate issue. (Please do, your suggestions look good)

**Comment by rtfeldman** [comment]
Closing in favor of https://github.com/elm-lang/error-message-catalog/issues/42
