### ISSUE TITLE
Output Conciseness

### ISSUE THREAD

**Issue by rtfeldman** [elm-lang/error-message-catalog#42]
Moving this here from https://github.com/elm-lang/error-message-catalog/issues/41

This is not a *confusing* error message, per say, but it does feel like it could be nicer with a bit of trimming and rearranging:

```
rtfeldman$ elm make ConciseErrors.elm

## ERRORS in ConciseErrors.elm #################################################

-- ERROR: TYPE MISMATCH --------------------------------------------- ConciseErrors.elm

The 1st argument to function `view` has an unexpected type.

8|        view { username = "", password = "" }
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Looks like a record is missing the field `errors`

As I infer the types of values flowing through your program, I see a conflict
between these two types:

    { b |
        errors : { a | password : String, username : String },
        password : String,
        username : String
        }

    { password : String, username : String }


Detected errors in 1 module. 
rtfeldman$
```

Based on how I use compiler output, I'd make 3 changes to this message:

1. "Bottom-line it for me" by putting the most helpful message first, namely `Looks like a record is missing the field 'errors'`
2. Cut the `### ERRORS #####` line - all I ever look at are the `-- TYPE MISMATCH -----` lines anyway.
3. Cut `Detected errors in 1 module.` - this has never been useful to me; seems like more of a candidate for a hypothetical `elm-make -v` or something.

```
rtfeldman$ elm make ConciseErrors.elm

-- ERROR: TYPE MISMATCH --------------------------------------------- ConciseErrors.elm

Looks like a record is missing the field `errors`

8|        view { username = "", password = "" }
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

The 1st argument to function `view` has an unexpected type. I see a conflict
between these two types:

    { b |
        errors : { a | password : String, username : String },
        password : String,
        username : String
        }

    { password : String, username : String }

rtfeldman$
```

**Comment by evancz** [comment]
The `####` is to separate errors from different modules. It's possible to get errors in 2 or more modules. Perhaps it'd be better to only include it when we need a separator?

**Comment by evancz** [comment]
It also separates warnings from errors iirc. I can imagine getting rid of that distinction, but I always hate when I can't tell if I'm seeing warnings or errors. Not sure on that piece.

**Comment by rtfeldman** [comment]
Do we need to separate errors in different modules so loudly though? What about just a quiet summary:

```
rtfeldman$ elm make ConciseErrors.elm

1 error, 0 warnings in ConciseErrors.elm

-- ERROR: TYPE MISMATCH --------------------------------------------- ConciseErrors.elm

Looks like a record is missing the field `errors`

8|        view { username = "", password = "" }
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

The 1st argument to function `view` has an unexpected type. I see a conflict
between these two types:

    { b |
        errors : { a | password : String, username : String },
        password : String,
        username : String
        }

    { password : String, username : String }

rtfeldman$
```

**Comment by evancz** [comment]
I'd wager there's a 99.99% chance that wouldn't help the intended audience.

When I do refactors on the compiler, I might break 4 to 8 modules at a time. I want to scroll through all that stuff as quickly as possible to find the relevant errors. The ugly `####` lines are something I can see during a speedy scroll.

**Comment by rtfeldman** [comment]
That's fair; makes sense to me why others would want that. Closing!

**Comment by evancz** [comment]
I think it makes sense to put it only if there are multiple files though. I'm currently working on error messages from elm-package and elm-make (in the same way I revamped elm-compiler) so I think it'd be good to do something like this.
