### ISSUE TITLE
Consider qualifying labels on simple Type errors

### ISSUE THREAD

**Issue by netaisllc** [elm-lang/error-message-catalog#44]
### Background
Coming from an untyped background, while I learn Elm I see messages regarding type mismatches quite a bit. But still, in the error text, I can never recall which is the _expected_ type and which is the _offending_ type. IKR.

### Suggestion
Revise these labels to evoke test assertions. That is, the type checker might inform 

>"I expected a type of **Int**, but your program uses a **Float**".  

Even such a small change would greatly impress anyone assessing the language as being worthy of a "learning-time" investment. 

A visual is attached.

![selection_119](https://cloud.githubusercontent.com/assets/1242423/10121225/9548e870-6496-11e5-8cd6-06dc82c5ec1b.png)

**Comment by Janiczek** [comment]
Oh man, me too. I usually can't figure out which one is the one I **have now** and which one is the **expected one**.
Infuariating when the two types are eg. Int and Float. Do I need `round` somewhere? `toFloat`? No idea, could be both ways.

**Comment by jvoigtlaender** [comment]
See https://github.com/elm-lang/elm-compiler/issues/1061, and be sure to read all of Evan's comments there.

**Comment by evancz** [comment]
This stuff is all going to be in 0.16 and it looks real nice :) Thanks for the report, excited to release the version that has this stuff!

**Comment by netaisllc** [comment]
Yep. I know... been lurking the -dev list.
Evan, what you are doing is stunningly great -- or should it be "insanely great" :)

**Comment by evancz** [comment]
Thanks :)
