### ISSUE TITLE
Better error when applying a non-function

### ISSUE THREAD

**Issue by mgold** [elm-lang/error-message-catalog#46]
If you try to apply a value, like `2 3`, you get this error message:

```
This function is expecting 0 argument, but was given 1.

3|   2 3
       ^
```

Let's leapfrog over how *argument* should be plural and talk about functions of zero arguments. To the compiler, yes definitions are just degenerate functions. But a better error message might be,

```
This value is not a function, but was given 1 argument.
``` 

Although it's less of a concern to me, the `^` points to the argument, but the line above it talks about the function. So ideally it would be `2` that is underlined.

The error takes a slightly different form when the 'function' is named.

```
>> e "to the i theta"

Function `e` is expecting 0 argument, but was given 1.

3|   e "to the i theta"
       ^^^^^^^^^^^^^^^^
```

It would be nice if the compiler didn't lie about `e` being a function. Again the argument is highlighted, but because the function is named, there's less confusion.

Implementing a fix should be a fairly simple check for zero.

**Comment by evancz** [comment]
Nice catch, I cleaned it up:

![screen shot 2015-10-28 at 3 30 36 pm](https://cloud.githubusercontent.com/assets/1658058/10805162/fc6d4c3e-7d88-11e5-9091-37ed23881eeb.png)

![screen shot 2015-10-28 at 3 30 14 pm](https://cloud.githubusercontent.com/assets/1658058/10805159/f8d6f8b8-7d88-11e5-8710-e796b5bac230.png)

I also added a note about "maybe you are missing a comma?" which kind of addresses #29 as well.
