### ISSUE TITLE
differentiate annotation errors from other type inference errors

### ISSUE THREAD

**Issue by rompetroll** [elm-lang/error-message-catalog#49]
Given this abbreviated code with a wrong type annotation on the `update` function
```
update: Action -> Model -> (Model, Effects)    
update action model =  ...

app = StartApp.start { init = initialModel, update = update, view = myview, inputs = [] }  

main = app.html
```

the current compiler (0.15.1) yields these error messages

```
Warning: ## ERRORS in src/index.elm #####################################################

-- TYPE MISMATCH ------------------------------------------------- src/index.elm

The 1st argument to function `start` has an unexpected type.

42|       StartApp.start
43|>    { init = initialModel
44|>    , update = update
45|>    , view = myview
46|>    , inputs = []
47|>    }

As I infer the type of values flowing through your program, I see a conflict
between these two types:

    Effects Action

    Effects


-- TYPE MISMATCH ------------------------------------------------- src/index.elm

The type annotation for `update` does not match its definition.

24| update: Action -> Model -> (Model, Effects)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
As I infer the type of values flowing through your program, I see a conflict
between these two types:

    Effects

    Effects Action Use --force to continue.

Aborted due to warnings.

```

The first error message bothers me. I do kind of understand why it's there (there is a type mismatch), but the error message is not helping.

So I wonder if it would be a good idea to let the compiler report type annotation mismatches only, until there are no more annotation errors. And only report other type errors in the absence of annotation errors.

**Comment by evancz** [comment]
Can you provide a http://sscce.org/ that triggers this message? I don't know how to reproduce this to ensure that it is gone now.

**Comment by rompetroll** [comment]
Here is a simpler, complete example
```
import Html exposing (..)
import Time exposing (..)

timeSignal: Signal
timeSignal = Time.every second

viewSignal: Signal Html
viewSignal = Signal.map (\ts -> text (toString ts)) timeSignal

main = viewSignal
```

Note the incomplete type annotation on `timeSignal`. Correct would be `timeSignal: Signal Float`.


The error output here is listed below. And I think it would be better to omit the error on line 8.

```
Detected errors in 1 module.
## ERRORS in example.elm #######################################################

-- TYPE MISMATCH --------------------------------------------------- example.elm

The 2nd argument to function `map` has an unexpected type.

8|              Signal.map (\ts -> text (toString ts)) timeSignal
                                                       ^^^^^^^^^^
As I infer the type of values flowing through your program, I see a conflict
between these two types:

    Signal a

    Signal


-- TYPE MISMATCH --------------------------------------------------- example.elm

The type annotation for `timeSignal` does not match its definition.

4| timeSignal: Signal
               ^^^^^^
As I infer the type of values flowing through your program, I see a conflict
between these two types:

    Signal

    Signal Float
```

**Comment by rompetroll** [comment]
Maybe worth mentioning: if I try a wrong (as opposed to incomplete) type annotation in the short example above, 

e.g. `timeSignal: Signal String`, 

then there is only one error message in line 4. like it should be IMO.

**Comment by evancz** [comment]
Here's what I'm seeing with 0.16:

![screen shot 2015-10-28 at 2 04 11 pm](https://cloud.githubusercontent.com/assets/1658058/10802961/ea0d9cd0-7d7c-11e5-81bc-342eb1c7bf1c.png)

Part of the improvements was figuring out how to avoid "cascading" errors where one wrong thing ended up producing a bunch of error messages that obscured the root thing.
