### ISSUE TITLE
Error message reporting weird types in failed type inference

### ISSUE THREAD

**Issue by zgotsch** [elm-lang/error-message-catalog#53]
I noticed that the types in the error resulting from this code were strange.
```
import Random exposing (..)

perturb' : Float -> Seed -> List Float -> (List Float, Seed)
perturb' dx seed xs = [1.0]
```

I get the error:

```
The type annotation for `perturb'` does not match its definition.

3| perturb' : Float -> Seed -> List Float -> (List Float, Seed)
As I infer the type of values flowing through your program, I see a conflict
between these two types:

    (List Float)

    List
```

And see the types `(List Float)` and `List`, when I should see `(List Float, Seed)` and `List Float`

**Comment by evancz** [comment]
Here's what I am seeing with 0.16:

![screen shot 2015-10-28 at 1 27 31 am](https://cloud.githubusercontent.com/assets/1658058/10783193/24007670-7d13-11e5-8d96-788358286f8d.png)

So I'm going to mark this as resolved. Thanks for the report!
