### ISSUE TITLE
Wrong module name when bootstrapping Elm in HTML file

### ISSUE THREAD

**Issue by Janiczek** [elm-lang/error-message-catalog#54]
In HTML I want to bootstrap Elm this way:
```html
    <script>
      Elm.fullscreen(Elm.TicketApps);
    </script>
```

but my module is called `TicketApp` (without the `s`).
When I try to load the page, it says:

```
Cannot read property 'make' of undefined


Open the developer console for more details.
```

(Opening the developer console doesn't really help at all.)
I propose adding checking for existence of the given module name in the `init()` function and outputting a more helpful error message, something along the lines of:

```
You wanted to embed Elm module "TicketApps".

I could not find any module of that name.

Maybe you meant:

    TicketApp
    TicketApp.Canvas
    Tests.TicketApp
```

**Comment by evancz** [comment]
This should be resolved in 0.17.1. You refer to things as `Elm.TicketApp.fullscreen()` so you still get a crappy JS error, but now it's more explicitly an JS problem. If you think there's some nicer way to do it in this world, make a new issue about that.
