### ISSUE TITLE
Improve compiler warning when trying to mutate modules

### ISSUE THREAD

**Issue by maxhoffmann** [elm-lang/error-message-catalog#55]
```
-- SYNTAX PROBLEM -------------------------------------------- repl-temp-000.elm

I ran into something unexpected when parsing your code!

4|   Mymodule.value = "trying to change this"
                    ^
I am looking for one of the following things:

    end of input
    whitespace
```

This error message could be improved for people who think modules are mutable.

**Comment by evancz** [comment]
Here is an attempt an an SSCCE to see how the new parser will handle it:

```elm
attemptAtSccee =
  let
    whatever =
      Mymodule.value = "trying to change this"
  in
    whatever
```

![screen shot 2016-12-15 at 7 38 26 pm](https://cloud.githubusercontent.com/assets/1658058/21248652/1d2733d4-c2fe-11e6-85ee-1b810236704a.png)

Here is another attempt an an SSCCE:

```elm
attemptAtSccee =
  Mymodule.value = "trying to change this"
```

![screen shot 2016-12-15 at 7 42 51 pm](https://cloud.githubusercontent.com/assets/1658058/21248745/c6c56a64-c2fe-11e6-94ec-8bfc3e70a5f2.png)

@maxhoffmann, in the future, please provide an http://sscce.org. That said, thanks for the report!
