### ISSUE TITLE
Sort "annotation mismatch" errors first

### ISSUE THREAD

**Issue by rtfeldman** [elm-lang/error-message-catalog#57]
This isn't a *confusing* error message, per se, but I've noticed that when I have several errors, some of which are annotation mismatches, I pretty much always work through them fastest if I resolve the annotation mismatches first. In particular this seems to unlock more useful error messages for the remaining errors.

As such, would it make sense to sort those to the top of the error list? That way if you just proceed through the errors in sequential order, you end up most often doing the most useful thing first.

**Comment by evancz** [comment]
I think trusting type annotations may change the calculus of this. I think it's worthwhile to open a new issue with an SSCCE based on experiences with 0.18

I suspect this was also before I figured out how to stop "cascading" errors. That should also mean that once you run into something bad, you do not continue creating errors based on it.
