### ISSUE TITLE
Conflict between exposed and local definitions not detected

### ISSUE THREAD

**Issue by mgold** [elm-lang/error-message-catalog#59]
If I import `map` from one module exposed, and also define `map` in this file, what happens?

``` elm
import Random
import List exposing (map)

map = Random.map

x = map identity [1..2]
```

```
-- TYPE MISMATCH ------------------------------------------------------ test.elm

The 2nd argument to function `map` is causing a mismatch.

6│     map identity [1..2]
                    ^^^^^^
Function `map` is expecting the 2nd argument to be:

    Random.Generator a

But it is:

    List number
```

The `map` used on the last line is the local one, referring to the Random module, not the one I imported from List.

Ideally this sort of name conflict would be detected and be an error itself.

**Comment by rtfeldman** [comment]
This seems like what I'd expect in a language that allows name shadowing.

That said, I personally try to avoid name shadowing but sometimes accidentally do it anyway (resulting in bugs), and I'd definitely be on board with the idea of name shadowing becoming a compiler error - including this case.

Obviously that's a separate discussion though. :smile:

**Comment by ghost** [comment]
> Ideally this sort of name conflict would be detected and be an error itself.

Yes, the same NAMING ERROR I get when there's a conflict with e.g. `toString` between Basics and a module I'm importing, e.g. Data.Integer.

**Comment by evancz** [comment]
The idea is that locally defined names always win.

It is easy to detect a clash between local and exposed values, but when you have `import Html exposing (..)` it can be a real pain for all the weird crap that is in there. Likewise, all files have `import Basics exposing (..)` by default, so you would not be able to use the names `min` or `max` locally.

In other words, the current behavior seems like the least bad option for the overall range of situations people are going to encounter.
