### ISSUE TITLE
Better errors for record access typos

### ISSUE THREAD

**Issue by danneu** [elm-lang/error-message-catalog#61]
I'm an Elm beginner and just got stuck on this error for maybe 15 minutes.

https://gist.github.com/danneu/bbdac2e3a1ba02b02668 (includes error + the small source file that failed to compile)

Error: 

``` Elm
The type annotation for `update` does not match its definition.

31│ update : Action -> Model -> Model
             ^^^^^^^^^^^^^^^^^^^^^^^^
The type annotation is saying:

    Action -> { ... } -> { ... }

But I am inferring that the definition has this type:

    Action -> { a | ..., powerlevel : ... } -> { a | ..., powerlevel : ... }
```

I was so stumped that I gisted my code to ask IRC or /r/elm if they could spot the problem. It was only seconds after I created the gist that I happened to see that on line 47 I access `model.powerlevel` instead of `model.powerLevel`.

Maybe my terminal font's `L` and `l` look too similar, but the end result was that I was stuck doing a line-by-line scan of the source code and it was only 100 lines long. 

Here's the culprit on line47:

``` Elm
    Tick ->
      let
        newPowerLevel = if model.powerlevel < 10 then
                          model.powerLevel + 1
                        else
                          model.powerLevel
```

I'm not sure what kind of solutions are possible to improve this error, but it would've been helpful to see line47 mentioned as the callsite that asserts the `.powerlevel` (typo'd) field that actually breaks the contract. That would've been great.

 Or even bring in Elm's precedent for "did you mean .powerLevel?" style typo help I've seen on other occasions.

**Comment by rtfeldman** [comment]
I wonder if this overlaps with https://github.com/elm-lang/error-message-catalog/issues/63 - how much do you think it would have helped if this line had been added to the end of the error message?

```
Hint: It looks like a record is missing the field `powerlevel`
```

**Comment by smerchek** [comment]
I've experienced this type of error several times over the last few days. I believe the crux of the problem is that the compiler is suggesting that the type annotation is wrong, but if I have annotated a function with a type definition, then I _know_ that the type is correct. It is the _usage_ of the type that is wrong. 

In this case, the usage of `powerlevel` should be pointed out as wrong because it does not conform to the type definition.

I would prefer the error is associated with line 47, something like below (with probably different verbiage):

```
The type Model does not have powerlevel.

47│ newPowerLevel = if model.powerlevel < 10 then
                       ^^^^^^^^^^^^^^^^

Hint: Did you mean model.powerLevel?
```

**Comment by danneu** [comment]
@smerchek Exactly, the compiler's error also roots you in the wrong headspace for tracking down what amounts to a typo rather than a mistyped domain model. Your proposed error message would be great.

@rtfeldman It seems that the main issue here is that the compiler error doesn't mention the point at which it discovered that I accessed the wrong field. Just mentioning line 47 would've been plenty sufficient.

"Hint: Did you mean model.powerLevel?" is icing on the cake, though you're still left in the dark without a a line number, especially if your typo is such that it can't determine a hint.

**Comment by ghost** [comment]
Yep, same. Just have to see the names of both fields in the error message to see the difference and make the connection.

**Comment by evancz** [comment]
I think this should be nicer as of 0.16, but I cannot test without a modern http://sscce.org/

So please open a new issue if you think the error from 0.17.1 can be better!
