### ISSUE TITLE
Type definition confused with function body

### ISSUE THREAD

**Issue by JoelQ** [elm-lang/error-message-catalog#62]
When I define a function and forget to add `:` before the type definition, I get the following error:

``` elm
view Model -> Html
view model =
  -- implementation
```

```
Detected errors in 1 module.
-- SYNTAX PROBLEM ----------------------------------------------------- Main.elm

I ran into something unexpected when parsing your code!

20│ view Model -> Html
               ^
I am looking for one of the following things:

    an equals sign '='
    whitespace
```

This message assumes I accidentally put type definitions into my function body and that the next character should be either `=` or ` `(whitespace). It ignores a third possibility, where I am actually trying to add a type definition and forgot the`:`.

Thoughts on adding that option to the error? It would then read like:

```
I am looking for one of the following things:

    a colon ':'
    an equals sign '='
    whitespace
```

**Comment by evancz** [comment]
Same as #142, but let's keep both open for now.

**Comment by evancz** [comment]
Thanks for the report! The error message was better in my development branch, but I made an extra change https://github.com/elm/compiler/commit/930d0de033f0e5eb36b5b87b3c46dc40b3ee8106 to make this case a bit nicer:

```
-- MISSING COLON? ----------------------------------------------------- temp.elm

I was not expecting to see an arrow here:

1| view Model -> Html
              ^^
This usually means a : is missing a bit earlier in a type annotation. It could
be something else though, so here is a valid definition for reference:

add : Int -> Int -> Int
add x y =
  x + y

Try to use that format with your `view` definition!

```

This is probably the most common case when a `->` is found like this, so hopefully it won't be too confusing if someone runs into this some other way.
