### ISSUE TITLE
Resurrect "Looks like a record is missing the field" as a Hint

### ISSUE THREAD

**Issue by rtfeldman** [elm-lang/error-message-catalog#63]
In [the 0.15.1 version of the live-validated signup form blog post](https://web.archive.org/web/20151124164745/http://tech.noredink.com/post/129641182738/building-a-live-validated-signup-form-in-elm) we had this error message:

```
-- TYPE MISMATCH ------------------------------------------------ SignupForm.elm

The 1st argument to function `view` has an unexpected type.

38|     view { username = "", password = "" }
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Looks like a record is missing the field `errors`

As I infer the type of values flowing through your program, I see a conflict
between these two types:

    { b |
        password : String,
        errors : { a | password : String, username : String },
        username : String
        }

    { password : String, username : String }
```

In 0.16, the same code yields this error instead:

```
-- TYPE MISMATCH ------------------------------------------------ SignupForm.elm

The argument to function `view` is causing a mismatch.

39│     view { username = "", password = "" }
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Function `view` is expecting the argument to be:

    { b | ..., errors : ... }

But it is:

    { ... }
```

It's easier to focus on what's wrong in the second case, but that one sentence "Looks like a record is missing the field `errors`" from the first one really made it clear what's going on, and also would probably help a newbie understand what the type diff is saying.

It seems like the best of both worlds would be to bring back "Looks like a record is missing the field `errors`" as a Hint:

```
-- TYPE MISMATCH ------------------------------------------------ SignupForm.elm

The argument to function `view` is causing a mismatch.

39│     view { username = "", password = "" }
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Function `view` is expecting the argument to be:

    { b | ..., errors : ... }

But it is:

    { ... }

Hint: It looks like a record is missing the field `errors`
```

**Comment by doppioslash** [comment]
+1
Someone who I have talked into using Elm is resenting the lack of this quite a bit ^^;

**Comment by evancz** [comment]
It should be pretty simple to fix, but I need an SSCCE.

**Comment by pdamoc** [comment]
here is a SSCCE: 

``` elm
import Html exposing (..)

type alias Model = 
  { username : String
  , password : String
  , errors : String 
  }

view : Model  -> Html msg 
view model = 
   text model.errors 

main =
   view { username = "", password = "" }
```

**Comment by rtfeldman** [comment]
Sweet, thank you @pdamoc! 🤘

**Comment by evancz** [comment]
Alright, should be back:

![screen shot 2016-08-10 at 12 03 10 am](https://cloud.githubusercontent.com/assets/1658058/17544741/f64f9b22-5e8d-11e6-8fd5-c706f30c3269.png)

It should also be nicer than ever in more complex cases. Like if there are multiple missing fields or many potential typos.

**Comment by rtfeldman** [comment]
THIS IS THE BEST WEEK
