### ISSUE TITLE
Confusing error message

### ISSUE THREAD

**Issue by gabriela-sartori** [elm-lang/error-message-catalog#70]
The error is that I need to convert the model.count with toString before using it in the `text` function, but the error is really confusing to newcomers.

![image](https://cloud.githubusercontent.com/assets/6143964/11617736/e8199e62-9c79-11e5-8157-22c2ebec3995.png)
![image](https://cloud.githubusercontent.com/assets/6143964/11617740/f037e568-9c79-11e5-87af-5e3befff425d.png)

**Comment by jvoigtlaender** [comment]
@mgold [proposed](https://github.com/elm-lang/elm-compiler/issues/1222#issuecomment-162394587) to deal with cases like this by some special handling in the compiler/type-checker: If "expected" and "actual" type differ only by one type having `String` at some place where the other type has something else, the error message could suggest that a call to `toString` might be needed somewhere.

(Actually, Max proposed something more restricted, namely making that suggestion only when the "inferred" type says `String` and the other one doesn't. But I assume the suggestion would also be useful in situations in which it is just the other way round.)

**Comment by mgold** [comment]
If I have an Int and need a String, `toString` is useful. If I have a String an need and Int, it's not. I'd like to avoid misleading hints, so _assuming inferred vs. annotated accurately capture this distinction_, I'd like to only provide the hint where appropriate.

Of course these would percolate up, so if the conflict was between _lists_ of Strings and Ints, you'd still get the hint.

A far more general solution would be to look at all (one argument?) functions in scope (and perhaps everything in core) and suggest everything that converts the inferred type to the expected/annotated type. So for instance, it knows when to suggest `toFloat : Int -> Float` and when to suggest `round, floor, ceil : Float -> Int`. Or back to our example, the compiler would suggest `toString : a -> String` in one case and `String.toInt : Int -> Result String Int` in the other. (You'd have to allow `Maybe a` and `Result x a` when looking for an `a` to find it, but still.) I believe this is similar to type holes?

**Comment by jvoigtlaender** [comment]
Well, your emphasized assumption is the crux, it seems. Is it valid? Also, more generally, who is the "I" in "If I have ... and need ..."? Is it really "you", the programmer who has and needs something? Or parts of your program? The caller or callee in an expression? To me, it seems there is no directionality here. Either one offers the hint "maybe add `toString` somewhere" (and I specifically wrote "somewhere" already in my comment above, not "at that place") whenever `Int` and `String` clash (in whatever "direction"), or not at all.

**Comment by gabriela-sartori** [comment]
The problem is that the compiler is accusing the wrong line to be the reason of the error, and infering the model.count is a String because I tried to use it as a String, instead of showing there that the function `text` expected a String instead a Int

**Comment by jvoigtlaender** [comment]
Let's try to test the hypothesis of the compiler being at fault here, on a simpler example.

Consider this code:

``` elm
type A = A
type B = B

f : A -> B
f x = x
```

About this, the compiler says:

```
The type annotation for `f` does not match its definition.
4| f : A -> B

The type annotation is saying:

    A -> B

But I am inferring that the definition has this type:

    A -> A
```

So the compiler is "accusing" the line `f : A -> B`.

@G4BB3R, is it a correct interpretation of your stance that the compiler should be accusing the line `f x = x` here instead?

**Comment by mgold** [comment]
Obviously I can't state someone else's opinion, but in this case it seems that there's just a mismatch, and one can't "accuse" the annotation or the definition specifically. They're both equally "guilty" (and equally "innocent").

However, why is the compiler inferring `A -> A`? The definition is `a -> a`, with type variables. Then it unifies `a` with `A`, and then _fails_ to unify inferred `A` with annotated `B`. Algorithmically this makes sense, but from an error message standpoint, I think it should print with type variables, as `B -> B` is just as plausibly the correct annotation.

**Comment by markhamburg** [comment]
When in doubt, I suspect from my own code — and I'll admit that I haven't been writing Elm code for very long — that the declaration is correct and the usage is wrong. Not always but the majority of the time. If the type checker assumes that the declaration is correct, I would hope that it would then be able to more precisely identify the point at which that type annotation fails to work within the function. Basically, the type annotation stands between the implementation and the uses. It establishes the types of the values that the implementation should expect and the types of values that callers of the function should supply.

**Comment by markhamburg** [comment]
Follow up/clarification on my comment. If the compiler "believed" the declaration, then the error that would be generated would be a report that at the point where the code says `text model.count`, it expects that `model.count` is an `Int` because of the type declaration for the function but `text` wants a `String`. While hinting that a `toString` may be called for is probably useful in this case, these sort of errors come up in lots of other contexts and it would be good to handle them in general based on believing the type declaration until it fails to work rather than deriving an actual type and then saying "hey, they don't match!" (One might still want to do the latter to detect insufficiently general type declarations though are those really errors?)

**Comment by evancz** [comment]
I think #154 will resolve this.

**Comment by evancz** [comment]
I have attempted to recreate the initial problem as an http://sscce.org/ and it looks like this:

``` elm
import Html exposing (..)

type Msg = Increment

type alias Model = { count : Int }

view : Model -> Html Msg
view model =
  div [] [ text model.count ]
```

With some changes I made recently, the resulting error is:

![screen shot 2016-09-20 at 3 48 24 pm](https://cloud.githubusercontent.com/assets/1658058/18691636/b2fe9120-7f49-11e6-8916-118e54441409.png)

**Comment by mgold** [comment]
For contrast, here is the error message produced by 0.17:

![image](https://cloud.githubusercontent.com/assets/1191970/18694540/d19dccde-7f5f-11e6-8a29-4aa059385c00.png)

My first reaction was that "but it is" doesn't reflect the fact that the `Int` comes from an annotation. "But it is annotated as" might be even better, although it could also be inferred, or used correctly elsewhere.

BUT, then I realized that `view` could be a really complex function, and you're only told the problem is in there somewhere. In the new version you're told exactly which function is causing the trouble. So this is a big improvement! 👏 👏 👏
