### ISSUE TITLE
Word 'find' doubled when compile with import a non-existent module

### ISSUE THREAD

**Issue by fobos** [elm-lang/error-message-catalog#79]
I tried to compile a program with importing a non-existent module

``` elm
import Graphics.Element exposing (..)
import Graphics.SomeModule -- <-- non-existent module

main = show "hello"
```

As a result I have error message with doubled word `find`

```
I cannot find find module 'Grapics.SomeModule'.
```

**Comment by jvoigtlaender** [comment]
This is already fixed: https://github.com/elm-lang/elm-make/commit/41f4b70fc2f75db5ff4dd6a18cd889b8e55154ff.

**Comment by fobos** [comment]
@jvoigtlaender Oh, great!
