### ISSUE TITLE
no line number given when EOF is reached with unbalanced parens

### ISSUE THREAD

**Issue by avh4** [elm-lang/error-message-catalog#9]
In this example

```elm
main = (
```

The following error message is produced:
```
-- SYNTAX PROBLEM ------------------------------------------------------------- 

I ran into something unexpected when parsing your code!


I am looking for one of the following things:

    whitespace
```

A more helpful message would point to the opening `(` on line 1, or at least state that it reached the end of file while looking for `whitespace`.

**Comment by jessitron** [comment]
I got this error (no line number, same message) without the parens - just forgetting to finish an infix expression.

```
module Bitty (..) where
f a b = a +
```

**Comment by evancz** [comment]
Tracking in meta issue #177

**Comment by evancz** [comment]
Been improving parser. The new message for this case is:

![screen shot 2016-12-15 at 7 54 25 pm](https://cloud.githubusercontent.com/assets/1658058/21248965/5e0a582a-c300-11e6-86b4-0a6b1f5c2105.png)

**Comment by evancz** [comment]
@jessitron's is different, and would be a good issue of its own. It is also improved by the new parser though:

![screen shot 2016-12-15 at 7 55 33 pm](https://cloud.githubusercontent.com/assets/1658058/21248985/7d7bd1de-c300-11e6-83ef-47172257a2bb.png)

**Comment by knewter** [comment]
Really happy to see error messages keep getting better.  This one was bothersome when I ran into it occasionally in larger files, and now it just won't be.  \o/
