### ISSUE TITLE
Messed up indentation on let, error could be better,

### ISSUE THREAD

**Issue by jessitron** [elm-lang/error-message-catalog#96]
This is probably not high priority, but could be more helpful, so here it is.

In this code, I have accidentally put the first declaration on the same line as the let.

```
module Bitty (..) where

something a =
  let s =
    f
      a
      "foo"
  in
    s

f a b = a + b
```

The error message says:

```
-- SYNTAX PROBLEM ---------------------------------------------------- Bitty.elm

I ran into something unexpected when parsing your code!

8│       "foo"
         ^
I am looking for one of the following things:

    an equals sign '='
    whitespace
```

Really, there is an indentation problem. It took me about 15 minutes to identify it, because the error did not help me.

**Comment by evancz** [comment]
I wrote a faster parser, and it also is producing nicer error messages. In this case, we now get:

![screen shot 2016-12-15 at 7 45 42 pm](https://cloud.githubusercontent.com/assets/1658058/21248793/1e1c5e30-c2ff-11e6-8403-b6107ad6527c.png)

Thank you for the report!
